CREATE TABLE `discountCodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(100) NOT NULL,
	`type` enum('percentage','fixed','free_shipping') NOT NULL,
	`value` int NOT NULL,
	`minOrderAmount` int,
	`maxUses` int,
	`usedCount` int NOT NULL DEFAULT 0,
	`startsAt` timestamp,
	`expiresAt` timestamp,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `discountCodes_id` PRIMARY KEY(`id`),
	CONSTRAINT `discountCodes_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `eventAttendees` (
	`id` int AUTO_INCREMENT NOT NULL,
	`registrationId` int NOT NULL,
	`eventId` int NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320),
	`phone` varchar(50),
	`ticketTypeId` int,
	`checkedInAt` timestamp,
	`qrCode` varchar(255),
	`dietaryRestrictions` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `eventAttendees_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `eventRegistrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` int NOT NULL,
	`userId` int,
	`ticketTypeId` int,
	`confirmationNumber` varchar(50) NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`quantity` int NOT NULL DEFAULT 1,
	`unitPrice` int NOT NULL,
	`total` int NOT NULL,
	`paymentStatus` enum('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
	`paymentIntentId` varchar(255),
	`status` enum('pending','confirmed','waitlisted','cancelled','attended','no_show') NOT NULL DEFAULT 'pending',
	`checkedInAt` timestamp,
	`dietaryRestrictions` text,
	`specialRequests` text,
	`customFields` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `eventRegistrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `eventRegistrations_confirmationNumber_unique` UNIQUE(`confirmationNumber`)
);
--> statement-breakpoint
CREATE TABLE `eventTicketTypes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`price` int NOT NULL,
	`quantity` int,
	`soldCount` int NOT NULL DEFAULT 0,
	`maxPerOrder` int DEFAULT 10,
	`salesStart` timestamp,
	`salesEnd` timestamp,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `eventTicketTypes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`shortDescription` text,
	`eventType` enum('workshop','retreat','webinar','meetup','conference','other') NOT NULL DEFAULT 'workshop',
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`timezone` varchar(100) DEFAULT 'America/Los_Angeles',
	`isAllDay` int NOT NULL DEFAULT 0,
	`locationType` enum('in_person','virtual','hybrid') NOT NULL DEFAULT 'in_person',
	`venue` varchar(255),
	`address` text,
	`city` varchar(100),
	`state` varchar(100),
	`country` varchar(100),
	`virtualUrl` varchar(500),
	`virtualPassword` varchar(100),
	`isFree` int NOT NULL DEFAULT 0,
	`price` int DEFAULT 0,
	`earlyBirdPrice` int,
	`earlyBirdDeadline` timestamp,
	`capacity` int,
	`registrationCount` int NOT NULL DEFAULT 0,
	`waitlistEnabled` int NOT NULL DEFAULT 0,
	`featuredImage` varchar(1000),
	`images` text,
	`registrationOpen` int NOT NULL DEFAULT 1,
	`registrationDeadline` timestamp,
	`requiresApproval` int NOT NULL DEFAULT 0,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`status` enum('draft','published','cancelled','completed') NOT NULL DEFAULT 'draft',
	`isFeatured` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`),
	CONSTRAINT `events_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `orderItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`productId` int NOT NULL,
	`variantId` int,
	`name` varchar(255) NOT NULL,
	`sku` varchar(100),
	`price` int NOT NULL,
	`quantity` int NOT NULL,
	`total` int NOT NULL,
	`imageUrl` varchar(1000),
	`options` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `orderItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(50) NOT NULL,
	`userId` int,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`status` enum('pending','processing','shipped','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`paymentStatus` enum('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
	`paymentMethod` varchar(50),
	`paymentIntentId` varchar(255),
	`subtotal` int NOT NULL,
	`discountAmount` int DEFAULT 0,
	`discountCode` varchar(100),
	`shippingAmount` int DEFAULT 0,
	`taxAmount` int DEFAULT 0,
	`total` int NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`shippingFirstName` varchar(100),
	`shippingLastName` varchar(100),
	`shippingAddress1` varchar(255),
	`shippingAddress2` varchar(255),
	`shippingCity` varchar(100),
	`shippingState` varchar(100),
	`shippingPostalCode` varchar(20),
	`shippingCountry` varchar(100),
	`billingFirstName` varchar(100),
	`billingLastName` varchar(100),
	`billingAddress1` varchar(255),
	`billingAddress2` varchar(255),
	`billingCity` varchar(100),
	`billingState` varchar(100),
	`billingPostalCode` varchar(20),
	`billingCountry` varchar(100),
	`trackingNumber` varchar(255),
	`trackingUrl` varchar(500),
	`shippedAt` timestamp,
	`deliveredAt` timestamp,
	`notes` text,
	`customerNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `productCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`imageUrl` varchar(1000),
	`parentId` int,
	`order` int NOT NULL DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `productCategories_id` PRIMARY KEY(`id`),
	CONSTRAINT `productCategories_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `productVariants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`sku` varchar(100),
	`price` int,
	`stock` int NOT NULL DEFAULT 0,
	`options` text,
	`imageUrl` varchar(1000),
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `productVariants_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`sku` varchar(100),
	`description` text,
	`shortDescription` text,
	`price` int NOT NULL,
	`compareAtPrice` int,
	`costPrice` int,
	`categoryId` int,
	`images` text,
	`featuredImage` varchar(1000),
	`stock` int NOT NULL DEFAULT 0,
	`lowStockThreshold` int DEFAULT 5,
	`trackInventory` int NOT NULL DEFAULT 1,
	`weight` int,
	`dimensions` text,
	`tags` text,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`status` enum('draft','active','archived') NOT NULL DEFAULT 'draft',
	`isFeatured` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_slug_unique` UNIQUE(`slug`),
	CONSTRAINT `products_sku_unique` UNIQUE(`sku`)
);
--> statement-breakpoint
CREATE TABLE `sectionBackgrounds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sectionKey` varchar(100) NOT NULL,
	`backgroundType` enum('color','image','video','gradient') NOT NULL DEFAULT 'color',
	`backgroundColor` varchar(50),
	`backgroundImage` varchar(1000),
	`backgroundVideo` varchar(1000),
	`gradientStart` varchar(50),
	`gradientEnd` varchar(50),
	`gradientDirection` varchar(50) DEFAULT 'to bottom',
	`overlayColor` varchar(50),
	`overlayOpacity` int DEFAULT 50,
	`backgroundPosition` varchar(50) DEFAULT 'center center',
	`backgroundSize` varchar(50) DEFAULT 'cover',
	`backgroundAttachment` enum('scroll','fixed') DEFAULT 'scroll',
	`isActive` int NOT NULL DEFAULT 1,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sectionBackgrounds_id` PRIMARY KEY(`id`),
	CONSTRAINT `sectionBackgrounds_sectionKey_unique` UNIQUE(`sectionKey`)
);
--> statement-breakpoint
CREATE TABLE `shoppingCarts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(255) NOT NULL,
	`userId` int,
	`items` text NOT NULL,
	`subtotal` int NOT NULL DEFAULT 0,
	`discountCode` varchar(100),
	`discountAmount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`expiresAt` timestamp,
	CONSTRAINT `shoppingCarts_id` PRIMARY KEY(`id`)
);
