DROP TABLE `adminSessions`;--> statement-breakpoint
DROP TABLE `adminUsers`;--> statement-breakpoint
DROP TABLE `aiChatConversations`;--> statement-breakpoint
DROP TABLE `aiFeedback`;--> statement-breakpoint
DROP TABLE `aiSettings`;--> statement-breakpoint
DROP TABLE `analyticsEvents`;--> statement-breakpoint
DROP TABLE `analyticsPageViews`;--> statement-breakpoint
DROP TABLE `analyticsSessions`;--> statement-breakpoint
DROP TABLE `articles`;--> statement-breakpoint
DROP TABLE `backups`;--> statement-breakpoint
DROP TABLE `blockTemplates`;--> statement-breakpoint
DROP TABLE `blockVersions`;--> statement-breakpoint
DROP TABLE `brandAssets`;--> statement-breakpoint
DROP TABLE `discountCodes`;--> statement-breakpoint
DROP TABLE `emailSettings`;--> statement-breakpoint
DROP TABLE `eventAttendees`;--> statement-breakpoint
DROP TABLE `eventRegistrations`;--> statement-breakpoint
DROP TABLE `eventTicketTypes`;--> statement-breakpoint
DROP TABLE `events`;--> statement-breakpoint
DROP TABLE `formFields`;--> statement-breakpoint
DROP TABLE `formSubmissions`;--> statement-breakpoint
DROP TABLE `media`;--> statement-breakpoint
DROP TABLE `navigation`;--> statement-breakpoint
DROP TABLE `orderItems`;--> statement-breakpoint
DROP TABLE `orders`;--> statement-breakpoint
DROP TABLE `pageBlocks`;--> statement-breakpoint
DROP TABLE `pages`;--> statement-breakpoint
DROP TABLE `productCategories`;--> statement-breakpoint
DROP TABLE `productVariants`;--> statement-breakpoint
DROP TABLE `products`;--> statement-breakpoint
DROP TABLE `redirects`;--> statement-breakpoint
DROP TABLE `sectionBackgrounds`;--> statement-breakpoint
DROP TABLE `seoSettings`;--> statement-breakpoint
DROP TABLE `shoppingCarts`;--> statement-breakpoint
DROP TABLE `siteContent`;--> statement-breakpoint
DROP TABLE `siteSettings`;--> statement-breakpoint
DROP TABLE `themeSettings`;--> statement-breakpoint
DROP TABLE `visitorProfiles`;