import {
  Type,
  Image,
  Video,
  Quote,
  MousePointer,
  Minus,
  Layout,
  Grid3X3,
  Star,
  DollarSign,
  ChevronDown,
  Layers,
  Clock,
  BarChart3,
  Images,
  FileText,
  Users,
  Building,
  MapPin,
  Calendar,
  MessageSquare,
  Mail,
  Phone,
  Share2,
  Download,
  Play,
  Music,
  Code,
  Table,
  List,
  CheckSquare,
  AlertCircle,
  Bookmark,
  Heart,
  ThumbsUp,
  Award,
  Zap,
  Target,
  TrendingUp,
  Globe,
  Shield,
  Sparkles,
  Palette,
  Box,
  Columns,
  LayoutGrid,
  Newspaper,
  LucideIcon,
  Feather,
  Flower2,
  Leaf,
  Mountain,
  Sun,
} from 'lucide-react';

export interface BlockType {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: BlockCategory;
  defaultContent: Record<string, unknown>;
  previewImage?: string;
  isJustEmpower?: boolean;  // Flag for JE-specific blocks
  premium?: boolean;        // Premium/advanced blocks
}

export type BlockCategory =
  | 'je-hero'        // JE hero sections
  | 'je-content'     // JE content blocks
  | 'je-media'       // JE media blocks
  | 'je-interactive' // JE interactive blocks
  | 'layout'
  | 'content'
  | 'media'
  | 'interactive'
  | 'data'
  | 'social'
  | 'commerce'
  | 'forms';

export const blockCategories: { id: BlockCategory; name: string; icon: LucideIcon; description?: string }[] = [
  { id: 'je-hero', name: '✦ JE Hero', icon: Flower2, description: 'JustEmpower hero sections' },
  { id: 'je-content', name: '✦ JE Content', icon: Feather, description: 'Brand-styled content blocks' },
  { id: 'je-media', name: '✦ JE Media', icon: Leaf, description: 'JustEmpower media blocks' },
  { id: 'je-interactive', name: '✦ JE Interactive', icon: Sun, description: 'JustEmpower interactive elements' },
  { id: 'layout', name: 'Layout', icon: Layout, description: 'Page structure blocks' },
  { id: 'content', name: 'Content', icon: Type, description: 'Text and content blocks' },
  { id: 'media', name: 'Media', icon: Image, description: 'Images, videos, and galleries' },
  { id: 'interactive', name: 'Interactive', icon: MousePointer, description: 'Buttons and interactive elements' },
  { id: 'data', name: 'Data & Charts', icon: BarChart3, description: 'Data visualization blocks' },
  { id: 'social', name: 'Social', icon: Share2, description: 'Social media integration' },
  { id: 'commerce', name: 'Commerce', icon: DollarSign, description: 'E-commerce blocks' },
  { id: 'forms', name: 'Forms', icon: FileText, description: 'Form and input blocks' },
];

export const blockTypes: BlockType[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER HERO BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-hero-video',
    name: 'JE Hero Video',
    description: 'Full-screen video hero with overlay content',
    icon: Play,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      videoUrl: '',
      posterImage: '',
      title: 'Catalyzing the Rise of Her.',
      titleColor: '#ffffff',
      subtitle: 'Welcome to Just Empower',
      subtitleColor: '#ffffff',
      description: 'Where Empowerment Becomes Embodiment.',
      descriptionColor: '#ffffff',
      ctaText: 'Discover More',
      ctaTextColor: '#ffffff',
      ctaLink: '/founder',
      overlayOpacity: 40,
      textAlignment: 'center',
      minHeight: '100vh',
      // Shape & Size
      borderRadius: '2.5rem',
      bottomCurve: true,
      // Content Position
      contentVerticalAlign: 'center',
      contentHorizontalAlign: 'center',
      contentMaxWidth: '4xl',
      // Spacing
      paddingTop: '16',
      paddingBottom: '16',
      paddingLeft: '6',
      paddingRight: '6',
      // Title Element Controls
      titleFontSize: '5rem',
      titleFontSizeMd: '7rem',
      titleFontSizeLg: '8rem',
      titleLineHeight: '1.1',
      titleMarginBottom: '1.5rem',
      titleFontWeight: '300',
      titleFontStyle: 'italic',
      // Subtitle Element Controls
      subtitleFontSize: '0.75rem',
      subtitleLetterSpacing: '0.3em',
      subtitleMarginBottom: '1.5rem',
      // Description Element Controls
      descriptionFontSize: '1.125rem',
      descriptionFontSizeMd: '1.25rem',
      descriptionLineHeight: '1.6',
      descriptionMarginBottom: '3rem',
      descriptionMaxWidth: '32rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '2rem',
      ctaPaddingY: '1rem',
      ctaFontSize: '0.875rem',
      ctaLetterSpacing: '0.2em',
      ctaBorderWidth: '1px',
    },
  },
  {
    id: 'je-hero-image',
    name: 'JE Hero Image',
    description: 'Full-screen image hero with elegant typography',
    icon: Image,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      title: 'Our Philosophy',
      titleColor: '#ffffff',
      subtitle: 'EMBODIMENT OVER INTELLECTUALIZATION',
      subtitleColor: '#ffffff',
      description: 'Truth begins where intellect ends—within the lived intelligence of the body and breath.',
      descriptionColor: '#ffffff',
      ctaText: '',
      ctaTextColor: '#ffffff',
      ctaLink: '',
      overlayOpacity: 30,
      textAlignment: 'center',
      minHeight: '80vh',
      // Shape & Size
      borderRadius: '2.5rem',
      bottomCurve: true,
      // Content Position
      contentVerticalAlign: 'center',
      contentHorizontalAlign: 'center',
      contentMaxWidth: '4xl',
      // Spacing
      paddingTop: '16',
      paddingBottom: '16',
      paddingLeft: '6',
      paddingRight: '6',
      // Title Element Controls
      titleFontSize: '5rem',
      titleFontSizeMd: '7rem',
      titleFontSizeLg: '8rem',
      titleLineHeight: '1.1',
      titleMarginBottom: '1.5rem',
      titleFontWeight: '300',
      titleFontStyle: 'italic',
      // Subtitle Element Controls
      subtitleFontSize: '0.75rem',
      subtitleLetterSpacing: '0.3em',
      subtitleMarginBottom: '1.5rem',
      // Description Element Controls
      descriptionFontSize: '1.125rem',
      descriptionFontSizeMd: '1.25rem',
      descriptionLineHeight: '1.6',
      descriptionMarginBottom: '3rem',
      descriptionMaxWidth: '32rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '2rem',
      ctaPaddingY: '1rem',
      ctaFontSize: '0.875rem',
      ctaLetterSpacing: '0.2em',
      ctaBorderWidth: '1px',
    },
  },
  {
    id: 'je-hero-split',
    name: 'JE Hero Split',
    description: 'Split hero with image and content side by side',
    icon: Columns,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      imagePosition: 'right',
      title: 'Meet the Founder',
      titleColor: '',
      subtitle: 'APRIL GAMBARDELLA',
      subtitleColor: '',
      description: 'A visionary leader dedicated to feminine empowerment...',
      descriptionColor: '',
      ctaText: 'Learn More',
      ctaTextColor: '',
      ctaLink: '/founder',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER CONTENT BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-section-standard',
    name: 'JE Section Standard',
    description: 'Standard content section with JE styling',
    icon: Box,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'OUR APPROACH',
      labelColor: '',
      title: 'The Philosophy',
      titleColor: '',
      description: 'Just Empower operates at the intersection of personal reclamation and collective influence.',
      descriptionColor: '',
      imageUrl: '',
      imagePosition: 'right',
      ctaText: 'Learn More',
      ctaTextColor: '',
      ctaLink: '/philosophy',
      backgroundColor: 'cream',
      // Image Element Controls
      imageWidth: '100%',
      imageHeight: 'auto',
      imageMaxWidth: '100%',
      imageBorderRadius: '2rem',
      imageObjectFit: 'cover',
      imageMarginTop: '0',
      imageMarginBottom: '0',
      // Text Element Controls
      titleFontSize: '3rem',
      titleLineHeight: '1.2',
      titleMarginBottom: '2rem',
      descriptionFontSize: '1.125rem',
      descriptionLineHeight: '1.75',
      descriptionMarginBottom: '2rem',
      labelFontSize: '0.75rem',
      labelMarginBottom: '1rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '1.5rem',
      ctaPaddingY: '0.75rem',
      ctaFontSize: '0.875rem',
      // Layout Controls
      contentGap: '4rem',
      sectionPaddingY: '6rem',
      sectionPaddingX: '1.5rem',
      contentTextAlign: 'left',
      contentVerticalAlign: 'center',
    },
  },
  {
    id: 'je-section-fullwidth',
    name: 'JE Section Full Width',
    description: 'Full-width section with background image/video',
    icon: Layout,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      backgroundType: 'image',
      backgroundUrl: '',
      overlayOpacity: 50,
      label: 'COMMUNITY',
      labelColor: '#ffffff',
      title: 'Emerge With Us',
      titleColor: '#ffffff',
      description: 'We are planting seeds for a new paradigm—one rooted in consciousness, compassion, and sacred reciprocity.',
      descriptionColor: '#ffffff',
      ctaText: 'Walk With Us',
      ctaTextColor: '#ffffff',
      ctaLink: '/walk-with-us',
      textColor: 'light',
      // Text Element Controls
      titleFontSize: '3.5rem',
      titleLineHeight: '1.2',
      titleMarginBottom: '1.5rem',
      descriptionFontSize: '1.25rem',
      descriptionLineHeight: '1.75',
      descriptionMarginBottom: '2rem',
      labelFontSize: '0.75rem',
      labelMarginBottom: '1rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '2rem',
      ctaPaddingY: '1rem',
      ctaFontSize: '0.875rem',
      // Layout Controls
      minHeight: '70vh',
      sectionPaddingY: '6rem',
      sectionPaddingX: '1.5rem',
      contentMaxWidth: '48rem',
      contentTextAlign: 'center',
      contentVerticalAlign: 'center',
    },
  },
  {
    id: 'je-pillars',
    name: 'JE Three Pillars',
    description: 'Display the three foundational pillars with editable titles and descriptions',
    icon: Mountain,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'FOUNDATION OF OUR WORK',
      title: 'The Three Pillars',
      description: 'Our work is built upon three interconnected pillars that guide everything we do.',
      dark: false,
      pillars: [
        { title: 'Embodiment', description: 'Living wisdom through the body, honoring our physical vessel as sacred ground for transformation.', icon: 'heart' },
        { title: 'Sacred Reciprocity', description: 'Honoring the give and take of life, creating balanced exchanges that nourish all involved.', icon: 'sparkles' },
        { title: 'Feminine Wisdom', description: 'Reclaiming ancient knowing, intuitive guidance, and the power of the feminine principle.', icon: 'crown' },
      ],
      imageUrl: '',
    },
  },
  {
    id: 'je-principles',
    name: 'JE Foundational Principles',
    description: 'Display numbered principles with descriptions - full sizing controls',
    icon: List,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: '',
      title: 'Foundational Principles',
      subtitle: '',
      columns: 2,
      dark: false,
      // Sizing controls matching original site
      sectionPadding: 'spacious',
      titleSize: 'large',
      subtitleSize: 'medium',
      numberSize: 'large',
      descriptionSize: 'medium',
      itemGap: 'spacious',
      headerMargin: 'mb-16 md:mb-24',
      maxWidth: 'max-w-6xl',
      principles: [
        { number: '01', title: 'Embodiment', description: 'Real change happens not in the mind alone, but in the body—where wisdom lives, where patterns are held, and where transformation takes root.', imageUrl: '' },
        { number: '02', title: 'Sacred Reciprocity', description: 'We honor the give and take of life, creating balanced exchanges that nourish all involved and honor the interconnection of all things.', imageUrl: '' },
        { number: '03', title: 'Feminine Wisdom', description: 'We honor the intelligence of the feminine—intuition, receptivity, cycles, and the deep knowing that arises from stillness and presence.', imageUrl: '' },
      ],
    },
  },
  {
    id: 'je-heading',
    name: 'JE Heading',
    description: 'Elegant heading with optional label',
    icon: Type,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'SECTION LABEL',
      title: 'Section Title',
      alignment: 'center',
      size: 'large',
      fontFamily: 'serif',
    },
  },
  {
    id: 'je-paragraph',
    name: 'JE Paragraph',
    description: 'Styled paragraph with JE typography',
    icon: Type,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      text: 'Your paragraph content here. This block supports rich text formatting.',
      alignment: 'left',
      maxWidth: '65ch',
      fontSize: 'base',
    },
  },
  {
    id: 'je-blockquote',
    name: 'JE Blockquote',
    description: 'Elegant quote with decorative styling',
    icon: Quote,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      quote: 'A meaningful quote to emphasize...',
      author: '',
      style: 'elegant',
      alignment: 'center',
    },
  },
  {
    id: 'je-newsletter',
    name: 'JE Newsletter',
    description: 'Newsletter signup with JE styling',
    icon: Mail,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'Deepen Your Practice',
      description: 'Subscribe to receive wisdom, offerings, and invitations to sacred gatherings.',
      buttonText: 'Subscribe',
      placeholder: 'Enter your email',
      backgroundColor: 'dark',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER MEDIA BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-image',
    name: 'JE Image',
    description: 'Image with reveal animation and JE styling',
    icon: Image,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      alt: '',
      caption: '',
      width: 'large',
      alignment: 'center',
      rounded: true,
      shadow: 'medium',
      revealAnimation: true,
    },
  },
  {
    id: 'je-video',
    name: 'JE Video',
    description: 'Video player with custom controls',
    icon: Video,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      videoUrl: '',
      posterImage: '',
      autoplay: false,
      loop: false,
      muted: false,
      controls: true,
      width: 'large',
      aspectRatio: '16/9',
    },
  },
  {
    id: 'je-gallery',
    name: 'JE Image Gallery',
    description: 'Masonry or grid gallery with lightbox',
    icon: Images,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      images: [
        { url: '', alt: 'Image 1', caption: '' },
        { url: '', alt: 'Image 2', caption: '' },
        { url: '', alt: 'Image 3', caption: '' },
      ],
      layout: 'grid',
      columns: 3,
      gap: 'medium',
      lightbox: true,
    },
  },
  {
    id: 'je-carousel',
    name: 'JE Carousel',
    description: 'Image/content carousel with elegant transitions',
    icon: Images,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      slides: [
        { title: 'Slide 1', description: 'Your first slide content', imageUrl: '', link: '' },
        { title: 'Slide 2', description: 'Your second slide content', imageUrl: '', link: '' },
      ],
      autoplay: true,
      interval: 5000,
      showDots: true,
      showArrows: true,
      transition: 'fade',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER INTERACTIVE BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-button',
    name: 'JE Button',
    description: 'Luxury styled button with multiple variants',
    icon: MousePointer,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      text: 'Learn More',
      link: '/',
      variant: 'primary',
      size: 'medium',
      fullWidth: false,
    },
  },
  {
    id: 'je-offerings-grid',
    name: 'JE Offerings Grid',
    description: 'Display offerings in a styled grid',
    icon: Grid3X3,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Our Offerings',
      subtitle: 'PATHWAYS TO TRANSFORMATION',
      offerings: [
        { title: 'Offering 1', description: 'Description of your first offering', imageUrl: '', price: '', link: '/' },
        { title: 'Offering 2', description: 'Description of your second offering', imageUrl: '', price: '', link: '/' },
        { title: 'Offering 3', description: 'Description of your third offering', imageUrl: '', price: '', link: '/' },
      ],
      columns: 3,
      showPrices: false,
    },
  },
  {
    id: 'je-testimonial',
    name: 'JE Testimonial',
    description: 'Elegant testimonial with JE styling',
    icon: Quote,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      quote: 'This experience transformed my life...',
      author: 'Jane Doe',
      role: 'Workshop Participant',
      imageUrl: '',
      style: 'elegant',
    },
  },
  {
    id: 'je-offerings-carousel',
    name: 'JE Offerings Carousel',
    description: 'Horizontal carousel showcasing offerings',
    icon: Images,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Our Offerings',
      subtitle: 'PATHWAYS TO TRANSFORMATION',
      showTitle: true,
      items: [
        { title: 'Offering 1', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 2', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 3', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 4', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 5', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 6', description: 'Description...', imageUrl: '', link: '' },
      ],
      autoplay: true,
      showArrows: true,
      showDots: true,
      // Shape & Size
      cardBorderRadius: '2rem',
      cardHeight: '400px',
      cardWidth: '30vw',
      // Spacing
      cardGap: '3rem',
      sectionPadding: '6rem',
    },
  },
  {
    id: 'je-community-section',
    name: 'JE Community Section',
    description: 'Community invitation section with background',
    icon: Users,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      backgroundType: 'video',
      backgroundUrl: '',
      overlayOpacity: 50,
      label: 'COMMUNITY',
      title: 'Emerge With Us',
      description: 'We are planting seeds for a new paradigm—one rooted in consciousness, compassion, and sacred reciprocity.',
      ctaText: 'Walk With Us',
      ctaLink: '/walk-with-us',
      features: [
        { icon: 'heart', title: 'Sacred Circles', description: 'Join our community gatherings' },
        { icon: 'star', title: 'Workshops', description: 'Transform through experience' },
        { icon: 'sun', title: 'Retreats', description: 'Immersive healing journeys' },
      ],
    },
  },
  {
    id: 'je-coming-soon',
    name: 'JE Coming Soon',
    description: 'Coming soon announcement section',
    icon: Clock,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      backgroundUrl: '',
      overlayOpacity: 60,
      label: 'COMING SOON',
      title: 'Rooted Unity',
      subtitle: 'Coming 2026',
      description: 'A new chapter in our journey of feminine empowerment.',
      ctaText: 'Join Waitlist',
      ctaLink: '/waitlist',
      showCountdown: false,
      launchDate: '',
    },
  },
  {
    id: 'je-volumes',
    name: 'JE Volumes Display',
    description: 'Display volumes/books in a grid',
    icon: Bookmark,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'The VI • X Journal Trilogy',
      subtitle: 'A JOURNEY IN THREE VOLUMES',
      volumes: [
        { title: 'Volume I: Seeds', description: 'Planting the seeds of transformation', imageUrl: '', link: '' },
        { title: 'Volume II: Roots', description: 'Growing deep foundations', imageUrl: '', link: '' },
        { title: 'Volume III: Bloom', description: 'Flourishing into your power', imageUrl: '', link: '' },
      ],
    },
  },
  {
    id: 'je-calendar',
    name: 'JE Calendar',
    description: 'Interactive event calendar with filtering',
    icon: Calendar,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Community Events',
      subtitle: 'GATHER WITH US',
      viewMode: 'calendar',
      showFilters: true,
      eventTypes: [
        { id: 'workshop', name: 'Workshop', color: '#FFD700' },
        { id: 'retreat', name: 'Retreat', color: '#22C55E' },
        { id: 'webinar', name: 'Webinar', color: '#14B8A6' },
        { id: 'meetup', name: 'Meetup', color: '#3B82F6' },
        { id: 'conference', name: 'Conference', color: '#EC4899' },
        { id: 'other', name: 'Other', color: '#6B7280' },
      ],
      events: [
        { date: '2026-02-15', title: 'Sample Workshop', type: 'workshop', description: 'A sample workshop event', link: '' },
        { date: '2026-03-01', title: 'Sample Retreat', type: 'retreat', description: 'A sample retreat event', link: '' },
      ],
      // Shape & Size
      borderRadius: '1.5rem',
      maxWidth: '6xl',
      // Spacing
      paddingTop: '24',
      paddingBottom: '24',
      paddingLeft: '6',
      paddingRight: '6',
      // Alignment
      contentAlign: 'center',
    },
  },
  {
    id: 'je-contact-form',
    name: 'JE Contact Form',
    description: 'Contact form with JE styling',
    icon: Mail,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Get In Touch',
      subtitle: 'WE\'D LOVE TO HEAR FROM YOU',
      description: 'Reach out to us for inquiries, collaborations, or just to say hello.',
      fields: [
        { name: 'name', label: 'Full Name', type: 'text', required: true },
        { name: 'email', label: 'Email Address', type: 'email', required: true },
        { name: 'subject', label: 'Subject', type: 'text', required: false },
        { name: 'message', label: 'Message', type: 'textarea', required: true },
      ],
      submitText: 'Send Message',
      successMessage: 'Thank you for reaching out. We\'ll be in touch soon.',
      // Shape & Size
      borderRadius: '1.5rem',
      maxWidth: '2xl',
      formWidth: '100%',
      // Spacing
      paddingTop: '24',
      paddingBottom: '24',
      paddingLeft: '6',
      paddingRight: '6',
      inputSpacing: '4',
      // Alignment
      contentAlign: 'center',
      formAlign: 'center',
    },
  },
  {
    id: 'je-faq',
    name: 'JE FAQ Accordion',
    description: 'Frequently asked questions with expandable answers',
    icon: ChevronDown,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'Frequently Asked Questions',
      subtitle: 'FIND ANSWERS',
      items: [
        { question: 'What is Just Empower?', answer: 'Just Empower is a platform for feminine empowerment...' },
        { question: 'How do I get started?', answer: 'You can begin your journey by...' },
        { question: 'What offerings are available?', answer: 'We offer workshops, retreats, and...' },
      ],
      style: 'elegant',
      allowMultiple: false,
    },
  },
  {
    id: 'je-footer',
    name: 'JE Footer',
    description: 'Site footer with navigation and branding',
    icon: Layout,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      logo: '',
      tagline: 'Catalyzing the Rise of Her.',
      columns: [
        { title: 'Navigate', links: [{ text: 'Home', url: '/' }, { text: 'Philosophy', url: '/philosophy' }] },
        { title: 'Offerings', links: [{ text: 'Workshops', url: '/offerings' }, { text: 'Retreats', url: '/offerings' }] },
        { title: 'Connect', links: [{ text: 'Contact', url: '/contact' }, { text: 'Walk With Us', url: '/walk-with-us' }] },
      ],
      socialLinks: [
        { platform: 'instagram', url: '' },
        { platform: 'facebook', url: '' },
        { platform: 'youtube', url: '' },
      ],
      copyright: '© 2025 Just Empower. All rights reserved.',
      showNewsletter: true,
    },
  },
  {
    id: 'je-two-column',
    name: 'JE Two Column',
    description: 'Two column layout with image and text',
    icon: Columns,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      imagePosition: 'left',
      label: '',
      title: 'Section Title',
      description: 'Your content here...',
      paragraph1: '',
      paragraph2: '',
      ctaText: '',
      ctaLink: '',
      backgroundColor: 'white',
    },
  },
  {
    id: 'je-feature-card',
    name: 'JE Feature Card',
    description: 'Individual feature card with icon',
    icon: Star,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      icon: 'star',
      title: 'Feature Title',
      description: 'Feature description...',
      link: '',
      style: 'elevated',
    },
  },
  {
    id: 'je-team-member',
    name: 'JE Team Member',
    description: 'Team or founder profile card',
    icon: Users,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      name: 'April Gambardella',
      role: 'Founder & Visionary',
      bio: 'A brief biography...',
      socialLinks: [
        { platform: 'instagram', url: '' },
        { platform: 'linkedin', url: '' },
      ],
      style: 'elegant',
    },
  },
  {
    id: 'je-divider',
    name: 'JE Divider',
    description: 'Decorative divider with JE styling',
    icon: Minus,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      style: 'elegant',
      width: 'medium',
      color: 'gold',
      spacing: 'medium',
    },
  },
  {
    id: 'je-spacer',
    name: 'JE Spacer',
    description: 'Vertical spacing block',
    icon: Minus,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      height: 'medium',
      showOnMobile: true,
    },
  },
  {
    id: 'je-rooted-unity',
    name: 'JE Rooted Unity',
    description: 'Two-column section with image/video and long-form text with preserved line breaks',
    icon: Leaf,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'ROOTED UNITY',
      title: 'Rooted Unity',
      subtitle: '',
      description: 'A short introduction to this section.',
      longDescription: 'This is a longer description that can contain multiple paragraphs.\n\nLine breaks are preserved, allowing for proper formatting of extended content.\n\nUse this field for detailed explanations, stories, or comprehensive descriptions.',
      imageUrl: '',
      videoUrl: '',
      ctaText: 'Learn More',
      ctaLink: '/learn-more',
      dark: true,
      reversed: false,
      imageBorderRadius: '2rem',
      features: ['Feature one', 'Feature two', 'Feature three'],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STANDARD LAYOUT BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  // Layout Blocks
  {
    id: 'hero',
    name: 'Hero Section',
    description: 'Full-width hero with headline, subtext, and CTA',
    icon: Layout,
    category: 'layout',
    defaultContent: {
      headline: 'Welcome to Our Platform',
      subheadline: 'Discover amazing possibilities',
      ctaText: 'Get Started',
      ctaLink: '#',
      backgroundImage: '',
      variant: 'centered',
      overlay: true,
    },
  },
  {
    id: 'columns',
    name: 'Columns',
    description: 'Multi-column layout container',
    icon: Columns,
    category: 'layout',
    defaultContent: {
      columns: 2,
      gap: 'medium',
      content: [{ html: '' }, { html: '' }],
    },
  },
  {
    id: 'section',
    name: 'Section',
    description: 'Container section with background options',
    icon: Box,
    category: 'layout',
    defaultContent: {
      backgroundColor: '',
      backgroundImage: '',
      padding: 'large',
      maxWidth: 'container',
    },
  },
  {
    id: 'grid',
    name: 'Grid Layout',
    description: 'Flexible grid container',
    icon: LayoutGrid,
    category: 'layout',
    defaultContent: {
      columns: 3,
      gap: 'medium',
      items: [],
    },
  },
  {
    id: 'spacer',
    name: 'Spacer',
    description: 'Add vertical spacing',
    icon: Minus,
    category: 'layout',
    defaultContent: {
      height: 64,
    },
  },
  {
    id: 'divider',
    name: 'Divider',
    description: 'Horizontal line separator',
    icon: Minus,
    category: 'layout',
    defaultContent: {
      style: 'solid',
      color: '#e5e7eb',
      width: '100%',
    },
  },

  // Content Blocks
  {
    id: 'text',
    name: 'Text Block',
    description: 'Rich text content with formatting',
    icon: Type,
    category: 'content',
    defaultContent: {
      content: '<p>Enter your text here...</p>',
      alignment: 'left',
    },
  },
  {
    id: 'heading',
    name: 'Heading',
    description: 'Section heading with multiple levels',
    icon: Type,
    category: 'content',
    defaultContent: {
      text: 'Section Heading',
      level: 'h2',
      alignment: 'left',
    },
  },
  {
    id: 'quote',
    name: 'Quote',
    description: 'Styled blockquote with attribution',
    icon: Quote,
    category: 'content',
    defaultContent: {
      quote: 'Enter your quote here...',
      author: 'Author Name',
      role: 'Position/Company',
      variant: 'default',
    },
  },
  {
    id: 'feature-grid',
    name: 'Feature Grid',
    description: 'Grid of features with icons',
    icon: Grid3X3,
    category: 'content',
    defaultContent: {
      heading: 'Our Features',
      features: [
        { icon: 'zap', title: 'Fast', description: 'Lightning fast performance' },
        { icon: 'shield', title: 'Secure', description: 'Enterprise-grade security' },
        { icon: 'sparkles', title: 'Modern', description: 'Built with latest tech' },
      ],
      columns: 3,
    },
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
    description: 'Customer testimonials carousel or grid',
    icon: Star,
    category: 'content',
    defaultContent: {
      heading: 'What Our Customers Say',
      testimonials: [
        {
          quote: 'Amazing product!',
          author: 'John Doe',
          role: 'CEO',
          company: 'Tech Corp',
          avatar: '',
          rating: 5,
        },
      ],
      variant: 'carousel',
    },
  },
  {
    id: 'team',
    name: 'Team Members',
    description: 'Team member profiles grid',
    icon: Users,
    category: 'content',
    defaultContent: {
      heading: 'Meet Our Team',
      members: [
        {
          name: 'Jane Smith',
          role: 'Founder & CEO',
          bio: 'Passionate about innovation',
          image: '',
          social: {},
        },
      ],
      columns: 4,
      variant: 'card',
    },
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Vertical or horizontal timeline',
    icon: Clock,
    category: 'content',
    defaultContent: {
      heading: 'Our Journey',
      events: [
        { date: '2020', title: 'Founded', description: 'Company was established' },
        { date: '2021', title: 'Growth', description: 'Expanded to new markets' },
      ],
      variant: 'vertical',
    },
  },
  {
    id: 'accordion',
    name: 'Accordion / FAQ',
    description: 'Collapsible content sections',
    icon: ChevronDown,
    category: 'content',
    defaultContent: {
      heading: 'Frequently Asked Questions',
      items: [
        { question: 'What is this?', answer: 'This is an FAQ section.' },
        { question: 'How does it work?', answer: 'Click to expand answers.' },
      ],
      allowMultiple: false,
    },
  },
  {
    id: 'tabs',
    name: 'Tabs',
    description: 'Tabbed content sections',
    icon: Layers,
    category: 'content',
    defaultContent: {
      tabs: [
        { label: 'Tab 1', content: 'Content for tab 1' },
        { label: 'Tab 2', content: 'Content for tab 2' },
      ],
      variant: 'default',
    },
  },
  {
    id: 'stats',
    name: 'Statistics',
    description: 'Number counters and stats',
    icon: TrendingUp,
    category: 'content',
    defaultContent: {
      stats: [
        { value: '10K+', label: 'Customers' },
        { value: '99%', label: 'Satisfaction' },
        { value: '24/7', label: 'Support' },
      ],
      variant: 'default',
    },
  },
  {
    id: 'logo-grid',
    name: 'Logo Grid',
    description: 'Partner/client logos display',
    icon: Building,
    category: 'content',
    defaultContent: {
      heading: 'Trusted By',
      logos: [],
      grayscale: true,
      columns: 5,
    },
  },
  {
    id: 'cta',
    name: 'Call to Action',
    description: 'Prominent CTA section',
    icon: MousePointer,
    category: 'content',
    defaultContent: {
      heading: 'Ready to Get Started?',
      description: 'Join thousands of satisfied customers today.',
      primaryButton: { text: 'Get Started', link: '#' },
      secondaryButton: { text: 'Learn More', link: '#' },
      variant: 'centered',
    },
  },
  {
    id: 'alert',
    name: 'Alert / Notice',
    description: 'Important announcements or notices',
    icon: AlertCircle,
    category: 'content',
    defaultContent: {
      message: 'Important notice here',
      type: 'info',
      dismissible: true,
    },
  },
  {
    id: 'list',
    name: 'List',
    description: 'Styled bullet or numbered list',
    icon: List,
    category: 'content',
    defaultContent: {
      items: ['Item 1', 'Item 2', 'Item 3'],
      style: 'bullet',
      icon: 'check',
    },
  },
  {
    id: 'checklist',
    name: 'Checklist',
    description: 'Interactive checklist',
    icon: CheckSquare,
    category: 'content',
    defaultContent: {
      heading: 'Checklist',
      items: [
        { text: 'Task 1', checked: true },
        { text: 'Task 2', checked: false },
      ],
    },
  },

  // Media Blocks
  {
    id: 'image',
    name: 'Image',
    description: 'Single image with caption',
    icon: Image,
    category: 'media',
    defaultContent: {
      src: '',
      alt: '',
      caption: '',
      size: 'full',
      alignment: 'center',
    },
  },
  {
    id: 'gallery',
    name: 'Image Gallery',
    description: 'Grid or masonry image gallery',
    icon: Images,
    category: 'media',
    defaultContent: {
      images: [],
      columns: 3,
      variant: 'grid',
      lightbox: true,
    },
  },
  {
    id: 'video',
    name: 'Video',
    description: 'Embedded video player',
    icon: Video,
    category: 'media',
    defaultContent: {
      url: '',
      provider: 'youtube',
      autoplay: false,
      controls: true,
    },
  },
  {
    id: 'video-background',
    name: 'Video Background',
    description: 'Full-width video background section',
    icon: Play,
    category: 'media',
    defaultContent: {
      videoUrl: '',
      overlayContent: {
        heading: '',
        subheading: '',
        cta: '',
      },
      overlay: true,
    },
  },
  {
    id: 'audio',
    name: 'Audio Player',
    description: 'Audio file player',
    icon: Music,
    category: 'media',
    defaultContent: {
      src: '',
      title: '',
      artist: '',
      showWaveform: false,
    },
  },
  {
    id: 'carousel',
    name: 'Carousel / Slider',
    description: 'Image or content carousel',
    icon: Images,
    category: 'media',
    defaultContent: {
      slides: [
        { title: 'Slide 1', description: 'Your first slide', imageUrl: '', link: '' },
        { title: 'Slide 2', description: 'Your second slide', imageUrl: '', link: '' },
      ],
      autoplay: true,
      interval: 5000,
      showDots: true,
      showArrows: true,
    },
  },
  {
    id: 'before-after',
    name: 'Before/After',
    description: 'Image comparison slider',
    icon: Columns,
    category: 'media',
    defaultContent: {
      beforeImage: '',
      afterImage: '',
      beforeLabel: 'Before',
      afterLabel: 'After',
    },
  },

  // Interactive Blocks
  {
    id: 'button',
    name: 'Button',
    description: 'Styled button with link',
    icon: MousePointer,
    category: 'interactive',
    defaultContent: {
      text: 'Click Me',
      link: '#',
      variant: 'primary',
      size: 'medium',
      icon: '',
    },
  },
  {
    id: 'button-group',
    name: 'Button Group',
    description: 'Multiple buttons together',
    icon: MousePointer,
    category: 'interactive',
    defaultContent: {
      buttons: [
        { text: 'Primary', link: '#', variant: 'primary' },
        { text: 'Secondary', link: '#', variant: 'outline' },
      ],
      alignment: 'center',
    },
  },
  {
    id: 'countdown',
    name: 'Countdown Timer',
    description: 'Countdown to a date/time',
    icon: Clock,
    category: 'interactive',
    defaultContent: {
      targetDate: '',
      heading: 'Coming Soon',
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
    },
  },
  {
    id: 'progress',
    name: 'Progress Bar',
    description: 'Visual progress indicator',
    icon: BarChart3,
    category: 'interactive',
    defaultContent: {
      items: [
        { label: 'Progress 1', value: 75 },
        { label: 'Progress 2', value: 50 },
      ],
      showPercentage: true,
      animated: true,
    },
  },
  {
    id: 'map',
    name: 'Map',
    description: 'Interactive map embed',
    icon: MapPin,
    category: 'interactive',
    defaultContent: {
      address: '',
      lat: 0,
      lng: 0,
      zoom: 14,
      style: 'default',
    },
  },
  {
    id: 'modal-trigger',
    name: 'Modal Trigger',
    description: 'Button that opens a modal',
    icon: Box,
    category: 'interactive',
    defaultContent: {
      triggerText: 'Open Modal',
      modalTitle: 'Modal Title',
      modalContent: '',
    },
  },

  // Data Blocks
  {
    id: 'table',
    name: 'Table',
    description: 'Data table with sorting',
    icon: Table,
    category: 'data',
    defaultContent: {
      headers: ['Column 1', 'Column 2', 'Column 3'],
      rows: [
        ['Data 1', 'Data 2', 'Data 3'],
        ['Data 4', 'Data 5', 'Data 6'],
      ],
      striped: true,
      sortable: true,
    },
  },
  {
    id: 'chart',
    name: 'Chart',
    description: 'Data visualization chart',
    icon: BarChart3,
    category: 'data',
    defaultContent: {
      type: 'bar',
      data: {
        labels: ['Jan', 'Feb', 'Mar'],
        datasets: [{ label: 'Sales', data: [10, 20, 30] }],
      },
      options: {},
    },
  },
  {
    id: 'pricing',
    name: 'Pricing Table',
    description: 'Pricing plans comparison',
    icon: DollarSign,
    category: 'data',
    defaultContent: {
      heading: 'Choose Your Plan',
      plans: [
        {
          name: 'Basic',
          price: '$9',
          period: 'month',
          features: ['Feature 1', 'Feature 2'],
          ctaText: 'Get Started',
          highlighted: false,
        },
        {
          name: 'Pro',
          price: '$29',
          period: 'month',
          features: ['All Basic', 'Feature 3', 'Feature 4'],
          ctaText: 'Get Started',
          highlighted: true,
        },
      ],
    },
  },
  {
    id: 'comparison',
    name: 'Comparison Table',
    description: 'Feature comparison grid',
    icon: Table,
    category: 'data',
    defaultContent: {
      heading: 'Compare Plans',
      features: ['Feature 1', 'Feature 2', 'Feature 3'],
      plans: [
        { name: 'Basic', values: [true, false, false] },
        { name: 'Pro', values: [true, true, false] },
        { name: 'Enterprise', values: [true, true, true] },
      ],
    },
  },

  // Social Blocks
  {
    id: 'social-links',
    name: 'Social Links',
    description: 'Social media icon links',
    icon: Share2,
    category: 'social',
    defaultContent: {
      links: [
        { platform: 'twitter', url: '' },
        { platform: 'facebook', url: '' },
        { platform: 'instagram', url: '' },
        { platform: 'linkedin', url: '' },
      ],
      style: 'icons',
      size: 'medium',
    },
  },
  {
    id: 'social-feed',
    name: 'Social Feed',
    description: 'Embedded social media feed',
    icon: Newspaper,
    category: 'social',
    defaultContent: {
      platform: 'instagram',
      username: '',
      count: 6,
    },
  },
  {
    id: 'share-buttons',
    name: 'Share Buttons',
    description: 'Social sharing buttons',
    icon: Share2,
    category: 'social',
    defaultContent: {
      platforms: ['twitter', 'facebook', 'linkedin', 'email'],
      style: 'buttons',
    },
  },
  {
    id: 'reviews',
    name: 'Reviews',
    description: 'Customer reviews with ratings',
    icon: Star,
    category: 'social',
    defaultContent: {
      heading: 'Customer Reviews',
      reviews: [],
      showRating: true,
      allowSubmit: false,
    },
  },

  // Commerce Blocks
  {
    id: 'product-card',
    name: 'Product Card',
    description: 'Single product display',
    icon: Box,
    category: 'commerce',
    defaultContent: {
      productId: '',
      showPrice: true,
      showDescription: true,
      showButton: true,
    },
  },
  {
    id: 'product-grid',
    name: 'Product Grid',
    description: 'Multiple products grid',
    icon: LayoutGrid,
    category: 'commerce',
    defaultContent: {
      products: [],
      columns: 4,
      showFilters: false,
    },
  },
  {
    id: 'featured-product',
    name: 'Featured Product',
    description: 'Highlighted product showcase',
    icon: Award,
    category: 'commerce',
    defaultContent: {
      productId: '',
      variant: 'hero',
      showGallery: true,
    },
  },

  // Form Blocks
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Pre-built contact form',
    icon: Mail,
    category: 'forms',
    defaultContent: {
      heading: 'Get in Touch',
      fields: ['name', 'email', 'message'],
      submitText: 'Send Message',
      successMessage: 'Thank you for your message!',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter Signup',
    description: 'Email subscription form',
    icon: Mail,
    category: 'forms',
    defaultContent: {
      heading: 'Subscribe to Our Newsletter',
      description: 'Get the latest updates delivered to your inbox.',
      buttonText: 'Subscribe',
      placeholder: 'Enter your email',
    },
  },
  {
    id: 'form-builder',
    name: 'Custom Form',
    description: 'Build custom forms',
    icon: FileText,
    category: 'forms',
    defaultContent: {
      fields: [],
      submitText: 'Submit',
      successMessage: 'Form submitted successfully!',
    },
  },
  {
    id: 'search',
    name: 'Search Box',
    description: 'Search input with suggestions',
    icon: Globe,
    category: 'forms',
    defaultContent: {
      placeholder: 'Search...',
      showSuggestions: true,
      searchType: 'site',
    },
  },

  // Special Blocks
  {
    id: 'code',
    name: 'Code Block',
    description: 'Syntax highlighted code',
    icon: Code,
    category: 'content',
    defaultContent: {
      code: '// Your code here',
      language: 'javascript',
      showLineNumbers: true,
      theme: 'dark',
    },
  },
  {
    id: 'embed',
    name: 'Embed',
    description: 'Embed external content',
    icon: Code,
    category: 'media',
    defaultContent: {
      embedCode: '',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'html',
    name: 'Custom HTML',
    description: 'Raw HTML content',
    icon: Code,
    category: 'content',
    defaultContent: {
      html: '',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 🎨 NEW BLOCK VARIATIONS - 50+ ENHANCED BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════

  // === HERO VARIATIONS ===
  {
    id: 'hero-parallax',
    name: 'Parallax Hero',
    description: 'Hero with parallax scrolling background effect',
    icon: Layers,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      title: 'Parallax Hero',
      subtitle: 'Immersive scrolling experience',
      backgroundImage: '',
      parallaxSpeed: 0.5,
      overlayOpacity: 40,
      minHeight: '100vh',
    },
  },
  {
    id: 'hero-gradient',
    name: 'Gradient Hero',
    description: 'Hero with animated gradient background',
    icon: Palette,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      title: 'Gradient Hero',
      subtitle: 'Beautiful flowing colors',
      gradientFrom: '#7c3aed',
      gradientTo: '#ec4899',
      gradientAngle: 135,
      animated: true,
      minHeight: '80vh',
    },
  },
  {
    id: 'hero-particles',
    name: 'Particles Hero',
    description: 'Hero with floating particle effects',
    icon: Sparkles,
    category: 'je-hero',
    isJustEmpower: true,
    premium: true,
    defaultContent: {
      title: 'Particles Hero',
      subtitle: 'Magical floating elements',
      particleCount: 50,
      particleColor: '#ffffff',
      backgroundColor: '#1a1a2e',
      minHeight: '100vh',
    },
  },
  {
    id: 'hero-carousel',
    name: 'Carousel Hero',
    description: 'Hero with sliding images/content',
    icon: Images,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      slides: [
        { title: 'Slide 1', subtitle: '', image: '', ctaText: 'Learn More', ctaLink: '' },
        { title: 'Slide 2', subtitle: '', image: '', ctaText: 'Learn More', ctaLink: '' },
      ],
      autoPlay: true,
      interval: 5000,
      showDots: true,
      showArrows: true,
    },
  },
  {
    id: 'hero-minimal',
    name: 'Minimal Hero',
    description: 'Clean, typography-focused hero',
    icon: Type,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      title: 'Less is More',
      subtitle: '',
      textAlign: 'center',
      backgroundColor: '#ffffff',
      textColor: '#000000',
      minHeight: '60vh',
    },
  },
  {
    id: 'hero-countdown',
    name: 'Countdown Hero',
    description: 'Hero with countdown timer',
    icon: Clock,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      title: 'Coming Soon',
      subtitle: 'Something amazing is on the way',
      targetDate: '',
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
      backgroundImage: '',
    },
  },

  // === CONTENT VARIATIONS ===
  {
    id: 'text-highlight',
    name: 'Highlighted Text',
    description: 'Text block with highlight effects',
    icon: Type,
    category: 'content',
    defaultContent: {
      content: 'Your highlighted text here',
      highlightColor: '#fef08a',
      highlightStyle: 'marker',
      fontSize: 'large',
    },
  },
  {
    id: 'pull-quote',
    name: 'Pull Quote',
    description: 'Large decorative quote',
    icon: Quote,
    category: 'content',
    defaultContent: {
      quote: 'A beautifully styled pull quote',
      author: '',
      style: 'elegant',
      fontSize: 'xl',
      alignment: 'center',
    },
  },
  {
    id: 'dropcap',
    name: 'Drop Cap Paragraph',
    description: 'Paragraph with decorative first letter',
    icon: Type,
    category: 'content',
    defaultContent: {
      content: 'Lorem ipsum dolor sit amet...',
      dropCapStyle: 'classic',
      dropCapColor: '#7c3aed',
    },
  },
  {
    id: 'callout-box',
    name: 'Callout Box',
    description: 'Highlighted information box',
    icon: AlertCircle,
    category: 'content',
    defaultContent: {
      title: 'Important Note',
      content: 'This is important information',
      type: 'info',
      icon: 'info',
      showBorder: true,
    },
  },
  {
    id: 'blockquote-card',
    name: 'Quote Card',
    description: 'Quote in a card format',
    icon: Quote,
    category: 'content',
    defaultContent: {
      quote: 'Your inspiring quote here',
      author: 'Author Name',
      authorTitle: 'Title/Role',
      authorImage: '',
      backgroundColor: '#f8fafc',
    },
  },
  {
    id: 'text-columns',
    name: 'Multi-Column Text',
    description: 'Text in newspaper-style columns',
    icon: Columns,
    category: 'content',
    defaultContent: {
      content: 'Your multi-column text content...',
      columns: 2,
      gap: 'medium',
    },
  },
  {
    id: 'definition-list',
    name: 'Definition List',
    description: 'Terms and definitions',
    icon: List,
    category: 'content',
    defaultContent: {
      items: [
        { term: 'Term 1', definition: 'Definition 1' },
        { term: 'Term 2', definition: 'Definition 2' },
      ],
      style: 'stacked',
    },
  },
  {
    id: 'feature-list',
    name: 'Feature List',
    description: 'List with icons and descriptions',
    icon: CheckSquare,
    category: 'content',
    defaultContent: {
      heading: 'Features',
      features: [
        { icon: 'check', title: 'Feature 1', description: 'Description' },
        { icon: 'check', title: 'Feature 2', description: 'Description' },
      ],
      style: 'grid',
      columns: 2,
    },
  },
  {
    id: 'comparison-list',
    name: 'Comparison List',
    description: 'Before/after or pros/cons list',
    icon: Columns,
    category: 'content',
    defaultContent: {
      leftTitle: 'Before',
      rightTitle: 'After',
      leftItems: ['Item 1', 'Item 2'],
      rightItems: ['Item 1', 'Item 2'],
      style: 'side-by-side',
    },
  },

  // === MEDIA VARIATIONS ===
  {
    id: 'image-compare',
    name: 'Image Comparison',
    description: 'Before/after image slider',
    icon: Images,
    category: 'media',
    defaultContent: {
      beforeImage: '',
      afterImage: '',
      beforeLabel: 'Before',
      afterLabel: 'After',
      orientation: 'horizontal',
    },
  },
  {
    id: 'image-hotspots',
    name: 'Image Hotspots',
    description: 'Image with clickable markers',
    icon: MapPin,
    category: 'media',
    premium: true,
    defaultContent: {
      image: '',
      hotspots: [],
      tooltipStyle: 'popup',
    },
  },
  {
    id: 'masonry-gallery',
    name: 'Masonry Gallery',
    description: 'Pinterest-style image grid',
    icon: LayoutGrid,
    category: 'media',
    defaultContent: {
      images: [],
      columns: 3,
      gap: 16,
      enableLightbox: true,
    },
  },
  {
    id: 'video-gallery',
    name: 'Video Gallery',
    description: 'Grid of video thumbnails',
    icon: Video,
    category: 'media',
    defaultContent: {
      videos: [],
      columns: 3,
      showTitles: true,
      autoplayOnHover: true,
    },
  },
  {
    id: 'audio-player',
    name: 'Audio Player',
    description: 'Styled audio player',
    icon: Music,
    category: 'media',
    defaultContent: {
      audioUrl: '',
      title: 'Audio Title',
      artist: '',
      coverImage: '',
      showWaveform: true,
    },
  },
  {
    id: 'podcast-player',
    name: 'Podcast Player',
    description: 'Podcast episode player',
    icon: Music,
    category: 'media',
    defaultContent: {
      episodeUrl: '',
      title: 'Episode Title',
      description: '',
      duration: '',
      showTranscript: false,
    },
  },
  {
    id: 'instagram-embed',
    name: 'Instagram Embed',
    description: 'Embed Instagram post',
    icon: Images,
    category: 'social',
    defaultContent: {
      postUrl: '',
      showCaption: true,
    },
  },
  {
    id: 'tiktok-embed',
    name: 'TikTok Embed',
    description: 'Embed TikTok video',
    icon: Video,
    category: 'social',
    defaultContent: {
      videoUrl: '',
    },
  },

  // === INTERACTIVE VARIATIONS ===
  {
    id: 'animated-counter',
    name: 'Animated Counter',
    description: 'Number that counts up on scroll',
    icon: TrendingUp,
    category: 'interactive',
    defaultContent: {
      numbers: [
        { value: 100, suffix: '+', label: 'Customers' },
        { value: 50, suffix: 'K', label: 'Downloads' },
      ],
      duration: 2000,
      triggerOnScroll: true,
    },
  },
  {
    id: 'progress-bars',
    name: 'Progress Bars',
    description: 'Animated skill/progress bars',
    icon: BarChart3,
    category: 'interactive',
    defaultContent: {
      heading: 'Skills',
      bars: [
        { label: 'Skill 1', value: 90, color: '#7c3aed' },
        { label: 'Skill 2', value: 75, color: '#ec4899' },
      ],
      animateOnScroll: true,
    },
  },
  {
    id: 'reveal-card',
    name: 'Reveal Card',
    description: 'Card that reveals content on hover',
    icon: Layers,
    category: 'interactive',
    defaultContent: {
      frontTitle: 'Hover Me',
      frontImage: '',
      backContent: 'Hidden content revealed!',
      revealDirection: 'up',
    },
  },
  {
    id: 'flip-card',
    name: 'Flip Card',
    description: '3D flipping card',
    icon: Layers,
    category: 'interactive',
    defaultContent: {
      frontTitle: 'Front',
      frontContent: 'Front content',
      backTitle: 'Back',
      backContent: 'Back content',
      flipDirection: 'horizontal',
    },
  },
  {
    id: 'hover-cards',
    name: 'Hover Effect Cards',
    description: 'Cards with various hover effects',
    icon: MousePointer,
    category: 'interactive',
    defaultContent: {
      cards: [
        { title: 'Card 1', description: '', image: '', link: '' },
        { title: 'Card 2', description: '', image: '', link: '' },
      ],
      hoverEffect: 'zoom',
      columns: 3,
    },
  },
  {
    id: 'floating-action',
    name: 'Floating Action Button',
    description: 'Fixed floating button',
    icon: MousePointer,
    category: 'interactive',
    defaultContent: {
      icon: 'message',
      label: 'Chat',
      link: '',
      position: 'bottom-right',
      style: 'circle',
    },
  },
  {
    id: 'scroll-progress',
    name: 'Scroll Progress',
    description: 'Progress bar showing scroll position',
    icon: BarChart3,
    category: 'interactive',
    defaultContent: {
      position: 'top',
      color: '#7c3aed',
      height: 4,
    },
  },
  {
    id: 'back-to-top',
    name: 'Back to Top',
    description: 'Scroll to top button',
    icon: ChevronDown,
    category: 'interactive',
    defaultContent: {
      showAfter: 300,
      style: 'circle',
      position: 'bottom-right',
    },
  },

  // === LAYOUT VARIATIONS ===
  {
    id: 'sticky-sidebar',
    name: 'Sticky Sidebar',
    description: 'Content with sticky side element',
    icon: Layout,
    category: 'layout',
    defaultContent: {
      mainContent: '',
      sidebarContent: '',
      sidebarPosition: 'right',
      sidebarWidth: '300px',
    },
  },
  {
    id: 'split-content',
    name: 'Split Content',
    description: '50/50 split layout',
    icon: Columns,
    category: 'layout',
    defaultContent: {
      leftContent: '',
      rightContent: '',
      leftBackground: '',
      rightBackground: '',
      gap: 0,
    },
  },
  {
    id: 'asymmetric-grid',
    name: 'Asymmetric Grid',
    description: 'Creative uneven grid layout',
    icon: LayoutGrid,
    category: 'layout',
    defaultContent: {
      items: [],
      pattern: 'featured-left',
      gap: 16,
    },
  },
  {
    id: 'bento-grid',
    name: 'Bento Grid',
    description: 'Modern bento box layout',
    icon: Grid3X3,
    category: 'layout',
    defaultContent: {
      items: [],
      columns: 4,
      rows: 3,
      gap: 16,
    },
  },
  {
    id: 'full-width-strip',
    name: 'Full Width Strip',
    description: 'Edge-to-edge content band',
    icon: Minus,
    category: 'layout',
    defaultContent: {
      content: '',
      backgroundColor: '#f8fafc',
      paddingY: 'large',
    },
  },
  {
    id: 'zigzag-layout',
    name: 'Zigzag Layout',
    description: 'Alternating left/right sections',
    icon: Layout,
    category: 'layout',
    defaultContent: {
      sections: [
        { title: 'Section 1', content: '', image: '' },
        { title: 'Section 2', content: '', image: '' },
      ],
      startPosition: 'image-left',
    },
  },

  // === DATA & CHARTS ===
  {
    id: 'pie-chart',
    name: 'Pie Chart',
    description: 'Circular data visualization',
    icon: BarChart3,
    category: 'data',
    defaultContent: {
      title: 'Distribution',
      data: [
        { label: 'Category A', value: 30, color: '#7c3aed' },
        { label: 'Category B', value: 70, color: '#ec4899' },
      ],
      showLegend: true,
      showPercentages: true,
    },
  },
  {
    id: 'line-chart',
    name: 'Line Chart',
    description: 'Trend line visualization',
    icon: TrendingUp,
    category: 'data',
    defaultContent: {
      title: 'Growth Over Time',
      labels: ['Jan', 'Feb', 'Mar', 'Apr'],
      datasets: [
        { label: 'Series 1', data: [10, 25, 15, 30], color: '#7c3aed' },
      ],
      showGrid: true,
    },
  },
  {
    id: 'bar-chart',
    name: 'Bar Chart',
    description: 'Vertical bar graph',
    icon: BarChart3,
    category: 'data',
    defaultContent: {
      title: 'Comparison',
      labels: ['A', 'B', 'C', 'D'],
      data: [25, 40, 30, 45],
      color: '#7c3aed',
      showValues: true,
    },
  },
  {
    id: 'data-table',
    name: 'Data Table',
    description: 'Styled data table',
    icon: Table,
    category: 'data',
    defaultContent: {
      headers: ['Column 1', 'Column 2', 'Column 3'],
      rows: [
        ['Data 1', 'Data 2', 'Data 3'],
        ['Data 4', 'Data 5', 'Data 6'],
      ],
      striped: true,
      hoverable: true,
    },
  },
  {
    id: 'comparison-table',
    name: 'Comparison Table',
    description: 'Feature comparison matrix',
    icon: Table,
    category: 'data',
    defaultContent: {
      features: ['Feature 1', 'Feature 2', 'Feature 3'],
      plans: [
        { name: 'Basic', values: [true, false, false] },
        { name: 'Pro', values: [true, true, false] },
        { name: 'Enterprise', values: [true, true, true] },
      ],
      highlightColumn: 1,
    },
  },

  // === SOCIAL BLOCKS ===
  {
    id: 'social-proof',
    name: 'Social Proof Bar',
    description: 'Trust badges and logos',
    icon: Shield,
    category: 'social',
    defaultContent: {
      heading: 'Trusted By',
      logos: [],
      style: 'scrolling',
    },
  },
  {
    id: 'twitter-feed',
    name: 'Twitter Feed',
    description: 'Display tweets',
    icon: MessageSquare,
    category: 'social',
    defaultContent: {
      username: '',
      tweetCount: 3,
      showMedia: true,
    },
  },
  {
    id: 'social-share',
    name: 'Social Share',
    description: 'Social sharing buttons',
    icon: Share2,
    category: 'social',
    defaultContent: {
      platforms: ['facebook', 'twitter', 'linkedin', 'email'],
      style: 'icons',
      showCount: false,
    },
  },
  {
    id: 'follow-buttons',
    name: 'Follow Buttons',
    description: 'Social follow buttons',
    icon: Users,
    category: 'social',
    defaultContent: {
      platforms: [
        { platform: 'instagram', url: '' },
        { platform: 'facebook', url: '' },
        { platform: 'youtube', url: '' },
      ],
      style: 'filled',
      showLabels: true,
    },
  },
  {
    id: 'user-reviews',
    name: 'User Reviews Carousel',
    description: 'Sliding customer reviews',
    icon: Star,
    category: 'social',
    defaultContent: {
      reviews: [],
      autoPlay: true,
      showRating: true,
      showAvatar: true,
    },
  },

  // === COMMERCE VARIATIONS ===
  {
    id: 'pricing-toggle',
    name: 'Pricing Toggle',
    description: 'Monthly/yearly price switch',
    icon: DollarSign,
    category: 'commerce',
    defaultContent: {
      plans: [],
      showMonthly: true,
      yearlyDiscount: 20,
      highlightedPlan: 1,
    },
  },
  {
    id: 'product-showcase',
    name: 'Product Showcase',
    description: 'Large product feature display',
    icon: Box,
    category: 'commerce',
    defaultContent: {
      productName: 'Product Name',
      tagline: '',
      features: [],
      mainImage: '',
      gallery: [],
      price: '',
      ctaText: 'Buy Now',
    },
  },
  {
    id: 'sale-banner',
    name: 'Sale Banner',
    description: 'Promotional banner',
    icon: Zap,
    category: 'commerce',
    defaultContent: {
      headline: 'Sale!',
      subheadline: 'Limited time offer',
      discount: '50% OFF',
      ctaText: 'Shop Now',
      ctaLink: '',
      backgroundColor: '#ef4444',
      endDate: '',
    },
  },
  {
    id: 'mini-cart',
    name: 'Mini Cart',
    description: 'Compact cart preview',
    icon: Box,
    category: 'commerce',
    defaultContent: {
      showItemCount: true,
      showTotal: true,
      position: 'top-right',
    },
  },

  // === FORM VARIATIONS ===
  {
    id: 'survey-form',
    name: 'Survey Form',
    description: 'Multi-step survey',
    icon: FileText,
    category: 'forms',
    defaultContent: {
      title: 'Quick Survey',
      questions: [],
      showProgress: true,
      allowSkip: false,
    },
  },
  {
    id: 'booking-form',
    name: 'Booking Form',
    description: 'Appointment scheduling',
    icon: Calendar,
    category: 'forms',
    defaultContent: {
      title: 'Book an Appointment',
      availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      timeSlots: ['9:00', '10:00', '11:00', '14:00', '15:00', '16:00'],
      collectInfo: ['name', 'email', 'phone'],
    },
  },
  {
    id: 'waitlist-form',
    name: 'Waitlist Form',
    description: 'Join waitlist signup',
    icon: Users,
    category: 'forms',
    defaultContent: {
      title: 'Join the Waitlist',
      description: 'Be the first to know when we launch',
      fields: ['email'],
      showPosition: true,
      incentive: '',
    },
  },
  {
    id: 'quiz-form',
    name: 'Quiz/Assessment',
    description: 'Interactive quiz builder',
    icon: CheckSquare,
    category: 'forms',
    premium: true,
    defaultContent: {
      title: 'Find Your Perfect Match',
      questions: [],
      showResults: true,
      resultTypes: [],
    },
  },
  {
    id: 'rating-form',
    name: 'Rating Widget',
    description: 'Star rating input',
    icon: Star,
    category: 'forms',
    defaultContent: {
      question: 'How would you rate your experience?',
      maxRating: 5,
      showLabels: true,
      collectFeedback: true,
    },
  },
];

export const getBlocksByCategory = (category: BlockCategory): BlockType[] => {
  return blockTypes.filter((block) => block.category === category);
};

export const getBlockById = (id: string): BlockType | undefined => {
  return blockTypes.find((block) => block.id === id);
};
