import {
  Type,
  Image,
  Video,
  Quote,
  MousePointer,
  Minus,
  Layout,
  Grid3X3,
  Star,
  DollarSign,
  ChevronDown,
  Layers,
  Clock,
  BarChart3,
  Images,
  FileText,
  Users,
  Building,
  MapPin,
  Calendar,
  MessageSquare,
  Mail,
  Phone,
  Share2,
  Download,
  Play,
  Music,
  Code,
  Table,
  List,
  CheckSquare,
  AlertCircle,
  Bookmark,
  Heart,
  ThumbsUp,
  Award,
  Zap,
  Target,
  TrendingUp,
  Globe,
  Shield,
  Sparkles,
  Palette,
  Box,
  Columns,
  LayoutGrid,
  Newspaper,
  LucideIcon,
  Feather,
  Flower2,
  Leaf,
  Mountain,
  Sun,
} from 'lucide-react';

export interface BlockType {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: BlockCategory;
  defaultContent: Record<string, unknown>;
  previewImage?: string;
  isJustEmpower?: boolean;  // Flag for JE-specific blocks
  premium?: boolean;        // Premium/advanced blocks
}

export type BlockCategory =
  | 'je-hero'        // JE hero sections
  | 'je-content'     // JE content blocks
  | 'je-media'       // JE media blocks
  | 'je-interactive' // JE interactive blocks
  | 'layout'
  | 'content'
  | 'media'
  | 'interactive'
  | 'data'
  | 'social'
  | 'commerce'
  | 'forms';

export const blockCategories: { id: BlockCategory; name: string; icon: LucideIcon; description?: string }[] = [
  { id: 'je-hero', name: '✦ JE Hero', icon: Flower2, description: 'JustEmpower hero sections' },
  { id: 'je-content', name: '✦ JE Content', icon: Feather, description: 'Brand-styled content blocks' },
  { id: 'je-media', name: '✦ JE Media', icon: Leaf, description: 'JustEmpower media blocks' },
  { id: 'je-interactive', name: '✦ JE Interactive', icon: Sun, description: 'JustEmpower interactive elements' },
  { id: 'layout', name: 'Layout', icon: Layout, description: 'Page structure blocks' },
  { id: 'content', name: 'Content', icon: Type, description: 'Text and content blocks' },
  { id: 'media', name: 'Media', icon: Image, description: 'Images, videos, and galleries' },
  { id: 'interactive', name: 'Interactive', icon: MousePointer, description: 'Buttons and interactive elements' },
  { id: 'data', name: 'Data & Charts', icon: BarChart3, description: 'Data visualization blocks' },
  { id: 'social', name: 'Social', icon: Share2, description: 'Social media integration' },
  { id: 'commerce', name: 'Commerce', icon: DollarSign, description: 'E-commerce blocks' },
  { id: 'forms', name: 'Forms', icon: FileText, description: 'Form and input blocks' },
];

export const blockTypes: BlockType[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER HERO BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-hero-video',
    name: 'JE Hero Video',
    description: 'Full-screen video hero with overlay content',
    icon: Play,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      videoUrl: '',
      posterImage: '',
      title: 'Catalyzing the Rise of Her.',
      titleColor: '#ffffff',
      subtitle: 'Welcome to Just Empower',
      subtitleColor: '#ffffff',
      description: 'Where Empowerment Becomes Embodiment.',
      descriptionColor: '#ffffff',
      ctaText: 'Discover More',
      ctaTextColor: '#ffffff',
      ctaLink: '/founder',
      overlayOpacity: 40,
      textAlignment: 'center',
      minHeight: '100vh',
      // Shape & Size
      borderRadius: '2.5rem',
      bottomCurve: true,
      // Content Position
      contentVerticalAlign: 'center',
      contentHorizontalAlign: 'center',
      contentMaxWidth: '4xl',
      // Spacing
      paddingTop: '16',
      paddingBottom: '16',
      paddingLeft: '6',
      paddingRight: '6',
      // Title Element Controls
      titleFontSize: '5rem',
      titleFontSizeMd: '7rem',
      titleFontSizeLg: '8rem',
      titleLineHeight: '1.1',
      titleMarginBottom: '1.5rem',
      titleFontWeight: '300',
      titleFontStyle: 'italic',
      // Subtitle Element Controls
      subtitleFontSize: '0.75rem',
      subtitleLetterSpacing: '0.3em',
      subtitleMarginBottom: '1.5rem',
      // Description Element Controls
      descriptionFontSize: '1.125rem',
      descriptionFontSizeMd: '1.25rem',
      descriptionLineHeight: '1.6',
      descriptionMarginBottom: '3rem',
      descriptionMaxWidth: '32rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '2rem',
      ctaPaddingY: '1rem',
      ctaFontSize: '0.875rem',
      ctaLetterSpacing: '0.2em',
      ctaBorderWidth: '1px',
    },
  },
  {
    id: 'je-hero-image',
    name: 'JE Hero Image',
    description: 'Full-screen image hero with elegant typography',
    icon: Image,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      title: 'Our Philosophy',
      titleColor: '#ffffff',
      subtitle: 'EMBODIMENT OVER INTELLECTUALIZATION',
      subtitleColor: '#ffffff',
      description: 'Truth begins where intellect ends—within the lived intelligence of the body and breath.',
      descriptionColor: '#ffffff',
      ctaText: '',
      ctaTextColor: '#ffffff',
      ctaLink: '',
      overlayOpacity: 30,
      textAlignment: 'center',
      minHeight: '80vh',
      // Shape & Size
      borderRadius: '2.5rem',
      bottomCurve: true,
      // Content Position
      contentVerticalAlign: 'center',
      contentHorizontalAlign: 'center',
      contentMaxWidth: '4xl',
      // Spacing
      paddingTop: '16',
      paddingBottom: '16',
      paddingLeft: '6',
      paddingRight: '6',
      // Title Element Controls
      titleFontSize: '5rem',
      titleFontSizeMd: '7rem',
      titleFontSizeLg: '8rem',
      titleLineHeight: '1.1',
      titleMarginBottom: '1.5rem',
      titleFontWeight: '300',
      titleFontStyle: 'italic',
      // Subtitle Element Controls
      subtitleFontSize: '0.75rem',
      subtitleLetterSpacing: '0.3em',
      subtitleMarginBottom: '1.5rem',
      // Description Element Controls
      descriptionFontSize: '1.125rem',
      descriptionFontSizeMd: '1.25rem',
      descriptionLineHeight: '1.6',
      descriptionMarginBottom: '3rem',
      descriptionMaxWidth: '32rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '2rem',
      ctaPaddingY: '1rem',
      ctaFontSize: '0.875rem',
      ctaLetterSpacing: '0.2em',
      ctaBorderWidth: '1px',
    },
  },
  {
    id: 'je-hero-split',
    name: 'JE Hero Split',
    description: 'Split hero with image and content side by side',
    icon: Columns,
    category: 'je-hero',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      imagePosition: 'right',
      title: 'Meet the Founder',
      titleColor: '',
      subtitle: 'APRIL GAMBARDELLA',
      subtitleColor: '',
      description: 'A visionary leader dedicated to feminine empowerment...',
      descriptionColor: '',
      ctaText: 'Learn More',
      ctaTextColor: '',
      ctaLink: '/founder',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER CONTENT BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-section-standard',
    name: 'JE Section Standard',
    description: 'Standard content section with JE styling',
    icon: Box,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'OUR APPROACH',
      labelColor: '',
      title: 'The Philosophy',
      titleColor: '',
      description: 'Just Empower operates at the intersection of personal reclamation and collective influence.',
      descriptionColor: '',
      imageUrl: '',
      imagePosition: 'right',
      ctaText: 'Learn More',
      ctaTextColor: '',
      ctaLink: '/philosophy',
      backgroundColor: 'cream',
      // Image Element Controls
      imageWidth: '100%',
      imageHeight: 'auto',
      imageMaxWidth: '100%',
      imageBorderRadius: '2rem',
      imageObjectFit: 'cover',
      imageMarginTop: '0',
      imageMarginBottom: '0',
      // Text Element Controls
      titleFontSize: '3rem',
      titleLineHeight: '1.2',
      titleMarginBottom: '2rem',
      descriptionFontSize: '1.125rem',
      descriptionLineHeight: '1.75',
      descriptionMarginBottom: '2rem',
      labelFontSize: '0.75rem',
      labelMarginBottom: '1rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '1.5rem',
      ctaPaddingY: '0.75rem',
      ctaFontSize: '0.875rem',
      // Layout Controls
      contentGap: '4rem',
      sectionPaddingY: '6rem',
      sectionPaddingX: '1.5rem',
      contentTextAlign: 'left',
      contentVerticalAlign: 'center',
    },
  },
  {
    id: 'je-section-fullwidth',
    name: 'JE Section Full Width',
    description: 'Full-width section with background image/video',
    icon: Layout,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      backgroundType: 'image',
      backgroundUrl: '',
      overlayOpacity: 50,
      label: 'COMMUNITY',
      labelColor: '#ffffff',
      title: 'Emerge With Us',
      titleColor: '#ffffff',
      description: 'We are planting seeds for a new paradigm—one rooted in consciousness, compassion, and sacred reciprocity.',
      descriptionColor: '#ffffff',
      ctaText: 'Walk With Us',
      ctaTextColor: '#ffffff',
      ctaLink: '/walk-with-us',
      textColor: 'light',
      // Text Element Controls
      titleFontSize: '3.5rem',
      titleLineHeight: '1.2',
      titleMarginBottom: '1.5rem',
      descriptionFontSize: '1.25rem',
      descriptionLineHeight: '1.75',
      descriptionMarginBottom: '2rem',
      labelFontSize: '0.75rem',
      labelMarginBottom: '1rem',
      // CTA Element Controls
      ctaBorderRadius: '9999px',
      ctaPaddingX: '2rem',
      ctaPaddingY: '1rem',
      ctaFontSize: '0.875rem',
      // Layout Controls
      minHeight: '70vh',
      sectionPaddingY: '6rem',
      sectionPaddingX: '1.5rem',
      contentMaxWidth: '48rem',
      contentTextAlign: 'center',
      contentVerticalAlign: 'center',
    },
  },
  {
    id: 'je-pillars',
    name: 'JE Three Pillars',
    description: 'Display the three foundational pillars with editable titles and descriptions',
    icon: Mountain,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'FOUNDATION OF OUR WORK',
      title: 'The Three Pillars',
      description: 'Our work is built upon three interconnected pillars that guide everything we do.',
      dark: false,
      pillars: [
        { title: 'Embodiment', description: 'Living wisdom through the body, honoring our physical vessel as sacred ground for transformation.', icon: 'heart' },
        { title: 'Sacred Reciprocity', description: 'Honoring the give and take of life, creating balanced exchanges that nourish all involved.', icon: 'sparkles' },
        { title: 'Feminine Wisdom', description: 'Reclaiming ancient knowing, intuitive guidance, and the power of the feminine principle.', icon: 'crown' },
      ],
      imageUrl: '',
    },
  },
  {
    id: 'je-principles',
    name: 'JE Foundational Principles',
    description: 'Display numbered principles with descriptions',
    icon: List,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'Foundational Principles',
      principles: [
        { number: '01', title: 'Embodiment', description: 'Real change happens not in the mind alone, but in the body...', imageUrl: '' },
        { number: '02', title: 'Sacred Reciprocity', description: 'We honor the give and take of life...', imageUrl: '' },
        { number: '03', title: 'Feminine Wisdom', description: 'We honor the intelligence of the feminine...', imageUrl: '' },
      ],
    },
  },
  {
    id: 'je-heading',
    name: 'JE Heading',
    description: 'Elegant heading with optional label',
    icon: Type,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'SECTION LABEL',
      title: 'Section Title',
      alignment: 'center',
      size: 'large',
      fontFamily: 'serif',
    },
  },
  {
    id: 'je-paragraph',
    name: 'JE Paragraph',
    description: 'Styled paragraph with JE typography',
    icon: Type,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      text: 'Your paragraph content here. This block supports rich text formatting.',
      alignment: 'left',
      maxWidth: '65ch',
      fontSize: 'base',
    },
  },
  {
    id: 'je-blockquote',
    name: 'JE Blockquote',
    description: 'Elegant quote with decorative styling',
    icon: Quote,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      quote: 'A meaningful quote to emphasize...',
      author: '',
      style: 'elegant',
      alignment: 'center',
    },
  },
  {
    id: 'je-newsletter',
    name: 'JE Newsletter',
    description: 'Newsletter signup with JE styling',
    icon: Mail,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'Deepen Your Practice',
      description: 'Subscribe to receive wisdom, offerings, and invitations to sacred gatherings.',
      buttonText: 'Subscribe',
      placeholder: 'Enter your email',
      backgroundColor: 'dark',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER MEDIA BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-image',
    name: 'JE Image',
    description: 'Image with reveal animation and JE styling',
    icon: Image,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      alt: '',
      caption: '',
      width: 'large',
      alignment: 'center',
      rounded: true,
      shadow: 'medium',
      revealAnimation: true,
    },
  },
  {
    id: 'je-video',
    name: 'JE Video',
    description: 'Video player with custom controls',
    icon: Video,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      videoUrl: '',
      posterImage: '',
      autoplay: false,
      loop: false,
      muted: false,
      controls: true,
      width: 'large',
      aspectRatio: '16/9',
    },
  },
  {
    id: 'je-gallery',
    name: 'JE Image Gallery',
    description: 'Masonry or grid gallery with lightbox',
    icon: Images,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      images: [
        { url: '', alt: 'Image 1', caption: '' },
        { url: '', alt: 'Image 2', caption: '' },
        { url: '', alt: 'Image 3', caption: '' },
      ],
      layout: 'grid',
      columns: 3,
      gap: 'medium',
      lightbox: true,
    },
  },
  {
    id: 'je-carousel',
    name: 'JE Carousel',
    description: 'Image/content carousel with elegant transitions',
    icon: Images,
    category: 'je-media',
    isJustEmpower: true,
    defaultContent: {
      slides: [
        { title: 'Slide 1', description: 'Your first slide content', imageUrl: '', link: '' },
        { title: 'Slide 2', description: 'Your second slide content', imageUrl: '', link: '' },
      ],
      autoplay: true,
      interval: 5000,
      showDots: true,
      showArrows: true,
      transition: 'fade',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ✦ JUSTXEMPOWER INTERACTIVE BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'je-button',
    name: 'JE Button',
    description: 'Luxury styled button with multiple variants',
    icon: MousePointer,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      text: 'Learn More',
      link: '/',
      variant: 'primary',
      size: 'medium',
      fullWidth: false,
    },
  },
  {
    id: 'je-offerings-grid',
    name: 'JE Offerings Grid',
    description: 'Display offerings in a styled grid',
    icon: Grid3X3,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Our Offerings',
      subtitle: 'PATHWAYS TO TRANSFORMATION',
      offerings: [
        { title: 'Offering 1', description: 'Description of your first offering', imageUrl: '', price: '', link: '/' },
        { title: 'Offering 2', description: 'Description of your second offering', imageUrl: '', price: '', link: '/' },
        { title: 'Offering 3', description: 'Description of your third offering', imageUrl: '', price: '', link: '/' },
      ],
      columns: 3,
      showPrices: false,
    },
  },
  {
    id: 'je-testimonial',
    name: 'JE Testimonial',
    description: 'Elegant testimonial with JE styling',
    icon: Quote,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      quote: 'This experience transformed my life...',
      author: 'Jane Doe',
      role: 'Workshop Participant',
      imageUrl: '',
      style: 'elegant',
    },
  },
  {
    id: 'je-offerings-carousel',
    name: 'JE Offerings Carousel',
    description: 'Horizontal carousel showcasing offerings',
    icon: Images,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Our Offerings',
      subtitle: 'PATHWAYS TO TRANSFORMATION',
      showTitle: true,
      items: [
        { title: 'Offering 1', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 2', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 3', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 4', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 5', description: 'Description...', imageUrl: '', link: '' },
        { title: 'Offering 6', description: 'Description...', imageUrl: '', link: '' },
      ],
      autoplay: true,
      showArrows: true,
      showDots: true,
      // Shape & Size
      cardBorderRadius: '2rem',
      cardHeight: '400px',
      cardWidth: '30vw',
      // Spacing
      cardGap: '3rem',
      sectionPadding: '6rem',
    },
  },
  {
    id: 'je-community-section',
    name: 'JE Community Section',
    description: 'Community invitation section with background',
    icon: Users,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      backgroundType: 'video',
      backgroundUrl: '',
      overlayOpacity: 50,
      label: 'COMMUNITY',
      title: 'Emerge With Us',
      description: 'We are planting seeds for a new paradigm—one rooted in consciousness, compassion, and sacred reciprocity.',
      ctaText: 'Walk With Us',
      ctaLink: '/walk-with-us',
      features: [
        { icon: 'heart', title: 'Sacred Circles', description: 'Join our community gatherings' },
        { icon: 'star', title: 'Workshops', description: 'Transform through experience' },
        { icon: 'sun', title: 'Retreats', description: 'Immersive healing journeys' },
      ],
    },
  },
  {
    id: 'je-coming-soon',
    name: 'JE Coming Soon',
    description: 'Coming soon announcement section',
    icon: Clock,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      backgroundUrl: '',
      overlayOpacity: 60,
      label: 'COMING SOON',
      title: 'Rooted Unity',
      subtitle: 'Coming 2026',
      description: 'A new chapter in our journey of feminine empowerment.',
      ctaText: 'Join Waitlist',
      ctaLink: '/waitlist',
      showCountdown: false,
      launchDate: '',
    },
  },
  {
    id: 'je-volumes',
    name: 'JE Volumes Display',
    description: 'Display volumes/books in a grid',
    icon: Bookmark,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'The VI • X Journal Trilogy',
      subtitle: 'A JOURNEY IN THREE VOLUMES',
      volumes: [
        { title: 'Volume I: Seeds', description: 'Planting the seeds of transformation', imageUrl: '', link: '' },
        { title: 'Volume II: Roots', description: 'Growing deep foundations', imageUrl: '', link: '' },
        { title: 'Volume III: Bloom', description: 'Flourishing into your power', imageUrl: '', link: '' },
      ],
    },
  },
  {
    id: 'je-calendar',
    name: 'JE Calendar',
    description: 'Interactive event calendar with filtering',
    icon: Calendar,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Community Events',
      subtitle: 'GATHER WITH US',
      viewMode: 'calendar',
      showFilters: true,
      eventTypes: [
        { id: 'workshop', name: 'Workshop', color: '#FFD700' },
        { id: 'retreat', name: 'Retreat', color: '#22C55E' },
        { id: 'webinar', name: 'Webinar', color: '#14B8A6' },
        { id: 'meetup', name: 'Meetup', color: '#3B82F6' },
        { id: 'conference', name: 'Conference', color: '#EC4899' },
        { id: 'other', name: 'Other', color: '#6B7280' },
      ],
      events: [
        { date: '2026-02-15', title: 'Sample Workshop', type: 'workshop', description: 'A sample workshop event', link: '' },
        { date: '2026-03-01', title: 'Sample Retreat', type: 'retreat', description: 'A sample retreat event', link: '' },
      ],
      // Shape & Size
      borderRadius: '1.5rem',
      maxWidth: '6xl',
      // Spacing
      paddingTop: '24',
      paddingBottom: '24',
      paddingLeft: '6',
      paddingRight: '6',
      // Alignment
      contentAlign: 'center',
    },
  },
  {
    id: 'je-contact-form',
    name: 'JE Contact Form',
    description: 'Contact form with JE styling',
    icon: Mail,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      title: 'Get In Touch',
      subtitle: 'WE\'D LOVE TO HEAR FROM YOU',
      description: 'Reach out to us for inquiries, collaborations, or just to say hello.',
      fields: [
        { name: 'name', label: 'Full Name', type: 'text', required: true },
        { name: 'email', label: 'Email Address', type: 'email', required: true },
        { name: 'subject', label: 'Subject', type: 'text', required: false },
        { name: 'message', label: 'Message', type: 'textarea', required: true },
      ],
      submitText: 'Send Message',
      successMessage: 'Thank you for reaching out. We\'ll be in touch soon.',
      // Shape & Size
      borderRadius: '1.5rem',
      maxWidth: '2xl',
      formWidth: '100%',
      // Spacing
      paddingTop: '24',
      paddingBottom: '24',
      paddingLeft: '6',
      paddingRight: '6',
      inputSpacing: '4',
      // Alignment
      contentAlign: 'center',
      formAlign: 'center',
    },
  },
  {
    id: 'je-faq',
    name: 'JE FAQ Accordion',
    description: 'Frequently asked questions with expandable answers',
    icon: ChevronDown,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      title: 'Frequently Asked Questions',
      subtitle: 'FIND ANSWERS',
      items: [
        { question: 'What is Just Empower?', answer: 'Just Empower is a platform for feminine empowerment...' },
        { question: 'How do I get started?', answer: 'You can begin your journey by...' },
        { question: 'What offerings are available?', answer: 'We offer workshops, retreats, and...' },
      ],
      style: 'elegant',
      allowMultiple: false,
    },
  },
  {
    id: 'je-footer',
    name: 'JE Footer',
    description: 'Site footer with navigation and branding',
    icon: Layout,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      logo: '',
      tagline: 'Catalyzing the Rise of Her.',
      columns: [
        { title: 'Navigate', links: [{ text: 'Home', url: '/' }, { text: 'Philosophy', url: '/philosophy' }] },
        { title: 'Offerings', links: [{ text: 'Workshops', url: '/offerings' }, { text: 'Retreats', url: '/offerings' }] },
        { title: 'Connect', links: [{ text: 'Contact', url: '/contact' }, { text: 'Walk With Us', url: '/walk-with-us' }] },
      ],
      socialLinks: [
        { platform: 'instagram', url: '' },
        { platform: 'facebook', url: '' },
        { platform: 'youtube', url: '' },
      ],
      copyright: '© 2025 Just Empower. All rights reserved.',
      showNewsletter: true,
    },
  },
  {
    id: 'je-two-column',
    name: 'JE Two Column',
    description: 'Two column layout with image and text',
    icon: Columns,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      imagePosition: 'left',
      label: '',
      title: 'Section Title',
      description: 'Your content here...',
      paragraph1: '',
      paragraph2: '',
      ctaText: '',
      ctaLink: '',
      backgroundColor: 'white',
    },
  },
  {
    id: 'je-feature-card',
    name: 'JE Feature Card',
    description: 'Individual feature card with icon',
    icon: Star,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      icon: 'star',
      title: 'Feature Title',
      description: 'Feature description...',
      link: '',
      style: 'elevated',
    },
  },
  {
    id: 'je-team-member',
    name: 'JE Team Member',
    description: 'Team or founder profile card',
    icon: Users,
    category: 'je-interactive',
    isJustEmpower: true,
    defaultContent: {
      imageUrl: '',
      name: 'April Gambardella',
      role: 'Founder & Visionary',
      bio: 'A brief biography...',
      socialLinks: [
        { platform: 'instagram', url: '' },
        { platform: 'linkedin', url: '' },
      ],
      style: 'elegant',
    },
  },
  {
    id: 'je-divider',
    name: 'JE Divider',
    description: 'Decorative divider with JE styling',
    icon: Minus,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      style: 'elegant',
      width: 'medium',
      color: 'gold',
      spacing: 'medium',
    },
  },
  {
    id: 'je-spacer',
    name: 'JE Spacer',
    description: 'Vertical spacing block',
    icon: Minus,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      height: 'medium',
      showOnMobile: true,
    },
  },
  {
    id: 'je-rooted-unity',
    name: 'JE Rooted Unity',
    description: 'Two-column section with image/video and long-form text with preserved line breaks',
    icon: Leaf,
    category: 'je-content',
    isJustEmpower: true,
    defaultContent: {
      label: 'ROOTED UNITY',
      title: 'Rooted Unity',
      subtitle: '',
      description: 'A short introduction to this section.',
      longDescription: 'This is a longer description that can contain multiple paragraphs.\n\nLine breaks are preserved, allowing for proper formatting of extended content.\n\nUse this field for detailed explanations, stories, or comprehensive descriptions.',
      imageUrl: '',
      videoUrl: '',
      ctaText: 'Learn More',
      ctaLink: '/learn-more',
      dark: true,
      reversed: false,
      imageBorderRadius: '2rem',
      features: ['Feature one', 'Feature two', 'Feature three'],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STANDARD LAYOUT BLOCKS
  // ═══════════════════════════════════════════════════════════════════════════
  // Layout Blocks
  {
    id: 'hero',
    name: 'Hero Section',
    description: 'Full-width hero with headline, subtext, and CTA',
    icon: Layout,
    category: 'layout',
    defaultContent: {
      headline: 'Welcome to Our Platform',
      subheadline: 'Discover amazing possibilities',
      ctaText: 'Get Started',
      ctaLink: '#',
      backgroundImage: '',
      variant: 'centered',
      overlay: true,
    },
  },
  {
    id: 'columns',
    name: 'Columns',
    description: 'Multi-column layout container',
    icon: Columns,
    category: 'layout',
    defaultContent: {
      columns: 2,
      gap: 'medium',
      content: [{ html: '' }, { html: '' }],
    },
  },
  {
    id: 'section',
    name: 'Section',
    description: 'Container section with background options',
    icon: Box,
    category: 'layout',
    defaultContent: {
      backgroundColor: '',
      backgroundImage: '',
      padding: 'large',
      maxWidth: 'container',
    },
  },
  {
    id: 'grid',
    name: 'Grid Layout',
    description: 'Flexible grid container',
    icon: LayoutGrid,
    category: 'layout',
    defaultContent: {
      columns: 3,
      gap: 'medium',
      items: [],
    },
  },
  {
    id: 'spacer',
    name: 'Spacer',
    description: 'Add vertical spacing',
    icon: Minus,
    category: 'layout',
    defaultContent: {
      height: 64,
    },
  },
  {
    id: 'divider',
    name: 'Divider',
    description: 'Horizontal line separator',
    icon: Minus,
    category: 'layout',
    defaultContent: {
      style: 'solid',
      color: '#e5e7eb',
      width: '100%',
    },
  },

  // Content Blocks
  {
    id: 'text',
    name: 'Text Block',
    description: 'Rich text content with formatting',
    icon: Type,
    category: 'content',
    defaultContent: {
      content: '<p>Enter your text here...</p>',
      alignment: 'left',
    },
  },
  {
    id: 'heading',
    name: 'Heading',
    description: 'Section heading with multiple levels',
    icon: Type,
    category: 'content',
    defaultContent: {
      text: 'Section Heading',
      level: 'h2',
      alignment: 'left',
    },
  },
  {
    id: 'quote',
    name: 'Quote',
    description: 'Styled blockquote with attribution',
    icon: Quote,
    category: 'content',
    defaultContent: {
      quote: 'Enter your quote here...',
      author: 'Author Name',
      role: 'Position/Company',
      variant: 'default',
    },
  },
  {
    id: 'feature-grid',
    name: 'Feature Grid',
    description: 'Grid of features with icons',
    icon: Grid3X3,
    category: 'content',
    defaultContent: {
      heading: 'Our Features',
      features: [
        { icon: 'zap', title: 'Fast', description: 'Lightning fast performance' },
        { icon: 'shield', title: 'Secure', description: 'Enterprise-grade security' },
        { icon: 'sparkles', title: 'Modern', description: 'Built with latest tech' },
      ],
      columns: 3,
    },
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
    description: 'Customer testimonials carousel or grid',
    icon: Star,
    category: 'content',
    defaultContent: {
      heading: 'What Our Customers Say',
      testimonials: [
        {
          quote: 'Amazing product!',
          author: 'John Doe',
          role: 'CEO',
          company: 'Tech Corp',
          avatar: '',
          rating: 5,
        },
      ],
      variant: 'carousel',
    },
  },
  {
    id: 'team',
    name: 'Team Members',
    description: 'Team member profiles grid',
    icon: Users,
    category: 'content',
    defaultContent: {
      heading: 'Meet Our Team',
      members: [
        {
          name: 'Jane Smith',
          role: 'Founder & CEO',
          bio: 'Passionate about innovation',
          image: '',
          social: {},
        },
      ],
      columns: 4,
      variant: 'card',
    },
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Vertical or horizontal timeline',
    icon: Clock,
    category: 'content',
    defaultContent: {
      heading: 'Our Journey',
      events: [
        { date: '2020', title: 'Founded', description: 'Company was established' },
        { date: '2021', title: 'Growth', description: 'Expanded to new markets' },
      ],
      variant: 'vertical',
    },
  },
  {
    id: 'accordion',
    name: 'Accordion / FAQ',
    description: 'Collapsible content sections',
    icon: ChevronDown,
    category: 'content',
    defaultContent: {
      heading: 'Frequently Asked Questions',
      items: [
        { question: 'What is this?', answer: 'This is an FAQ section.' },
        { question: 'How does it work?', answer: 'Click to expand answers.' },
      ],
      allowMultiple: false,
    },
  },
  {
    id: 'tabs',
    name: 'Tabs',
    description: 'Tabbed content sections',
    icon: Layers,
    category: 'content',
    defaultContent: {
      tabs: [
        { label: 'Tab 1', content: 'Content for tab 1' },
        { label: 'Tab 2', content: 'Content for tab 2' },
      ],
      variant: 'default',
    },
  },
  {
    id: 'stats',
    name: 'Statistics',
    description: 'Number counters and stats',
    icon: TrendingUp,
    category: 'content',
    defaultContent: {
      stats: [
        { value: '10K+', label: 'Customers' },
        { value: '99%', label: 'Satisfaction' },
        { value: '24/7', label: 'Support' },
      ],
      variant: 'default',
    },
  },
  {
    id: 'logo-grid',
    name: 'Logo Grid',
    description: 'Partner/client logos display',
    icon: Building,
    category: 'content',
    defaultContent: {
      heading: 'Trusted By',
      logos: [],
      grayscale: true,
      columns: 5,
    },
  },
  {
    id: 'cta',
    name: 'Call to Action',
    description: 'Prominent CTA section',
    icon: MousePointer,
    category: 'content',
    defaultContent: {
      heading: 'Ready to Get Started?',
      description: 'Join thousands of satisfied customers today.',
      primaryButton: { text: 'Get Started', link: '#' },
      secondaryButton: { text: 'Learn More', link: '#' },
      variant: 'centered',
    },
  },
  {
    id: 'alert',
    name: 'Alert / Notice',
    description: 'Important announcements or notices',
    icon: AlertCircle,
    category: 'content',
    defaultContent: {
      message: 'Important notice here',
      type: 'info',
      dismissible: true,
    },
  },
  {
    id: 'list',
    name: 'List',
    description: 'Styled bullet or numbered list',
    icon: List,
    category: 'content',
    defaultContent: {
      items: ['Item 1', 'Item 2', 'Item 3'],
      style: 'bullet',
      icon: 'check',
    },
  },
  {
    id: 'checklist',
    name: 'Checklist',
    description: 'Interactive checklist',
    icon: CheckSquare,
    category: 'content',
    defaultContent: {
      heading: 'Checklist',
      items: [
        { text: 'Task 1', checked: true },
        { text: 'Task 2', checked: false },
      ],
    },
  },

  // Media Blocks
  {
    id: 'image',
    name: 'Image',
    description: 'Single image with caption',
    icon: Image,
    category: 'media',
    defaultContent: {
      src: '',
      alt: '',
      caption: '',
      size: 'full',
      alignment: 'center',
    },
  },
  {
    id: 'gallery',
    name: 'Image Gallery',
    description: 'Grid or masonry image gallery',
    icon: Images,
    category: 'media',
    defaultContent: {
      images: [],
      columns: 3,
      variant: 'grid',
      lightbox: true,
    },
  },
  {
    id: 'video',
    name: 'Video',
    description: 'Embedded video player',
    icon: Video,
    category: 'media',
    defaultContent: {
      url: '',
      provider: 'youtube',
      autoplay: false,
      controls: true,
    },
  },
  {
    id: 'video-background',
    name: 'Video Background',
    description: 'Full-width video background section',
    icon: Play,
    category: 'media',
    defaultContent: {
      videoUrl: '',
      overlayContent: {
        heading: '',
        subheading: '',
        cta: '',
      },
      overlay: true,
    },
  },
  {
    id: 'audio',
    name: 'Audio Player',
    description: 'Audio file player',
    icon: Music,
    category: 'media',
    defaultContent: {
      src: '',
      title: '',
      artist: '',
      showWaveform: false,
    },
  },
  {
    id: 'carousel',
    name: 'Carousel / Slider',
    description: 'Image or content carousel',
    icon: Images,
    category: 'media',
    defaultContent: {
      slides: [
        { title: 'Slide 1', description: 'Your first slide', imageUrl: '', link: '' },
        { title: 'Slide 2', description: 'Your second slide', imageUrl: '', link: '' },
      ],
      autoplay: true,
      interval: 5000,
      showDots: true,
      showArrows: true,
    },
  },
  {
    id: 'before-after',
    name: 'Before/After',
    description: 'Image comparison slider',
    icon: Columns,
    category: 'media',
    defaultContent: {
      beforeImage: '',
      afterImage: '',
      beforeLabel: 'Before',
      afterLabel: 'After',
    },
  },

  // Interactive Blocks
  {
    id: 'button',
    name: 'Button',
    description: 'Styled button with link',
    icon: MousePointer,
    category: 'interactive',
    defaultContent: {
      text: 'Click Me',
      link: '#',
      variant: 'primary',
      size: 'medium',
      icon: '',
    },
  },
  {
    id: 'button-group',
    name: 'Button Group',
    description: 'Multiple buttons together',
    icon: MousePointer,
    category: 'interactive',
    defaultContent: {
      buttons: [
        { text: 'Primary', link: '#', variant: 'primary' },
        { text: 'Secondary', link: '#', variant: 'outline' },
      ],
      alignment: 'center',
    },
  },
  {
    id: 'countdown',
    name: 'Countdown Timer',
    description: 'Countdown to a date/time',
    icon: Clock,
    category: 'interactive',
    defaultContent: {
      targetDate: '',
      heading: 'Coming Soon',
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
    },
  },
  {
    id: 'progress',
    name: 'Progress Bar',
    description: 'Visual progress indicator',
    icon: BarChart3,
    category: 'interactive',
    defaultContent: {
      items: [
        { label: 'Progress 1', value: 75 },
        { label: 'Progress 2', value: 50 },
      ],
      showPercentage: true,
      animated: true,
    },
  },
  {
    id: 'map',
    name: 'Map',
    description: 'Interactive map embed',
    icon: MapPin,
    category: 'interactive',
    defaultContent: {
      address: '',
      lat: 0,
      lng: 0,
      zoom: 14,
      style: 'default',
    },
  },
  {
    id: 'modal-trigger',
    name: 'Modal Trigger',
    description: 'Button that opens a modal',
    icon: Box,
    category: 'interactive',
    defaultContent: {
      triggerText: 'Open Modal',
      modalTitle: 'Modal Title',
      modalContent: '',
    },
  },

  // Data Blocks
  {
    id: 'table',
    name: 'Table',
    description: 'Data table with sorting',
    icon: Table,
    category: 'data',
    defaultContent: {
      headers: ['Column 1', 'Column 2', 'Column 3'],
      rows: [
        ['Data 1', 'Data 2', 'Data 3'],
        ['Data 4', 'Data 5', 'Data 6'],
      ],
      striped: true,
      sortable: true,
    },
  },
  {
    id: 'chart',
    name: 'Chart',
    description: 'Data visualization chart',
    icon: BarChart3,
    category: 'data',
    defaultContent: {
      type: 'bar',
      data: {
        labels: ['Jan', 'Feb', 'Mar'],
        datasets: [{ label: 'Sales', data: [10, 20, 30] }],
      },
      options: {},
    },
  },
  {
    id: 'pricing',
    name: 'Pricing Table',
    description: 'Pricing plans comparison',
    icon: DollarSign,
    category: 'data',
    defaultContent: {
      heading: 'Choose Your Plan',
      plans: [
        {
          name: 'Basic',
          price: '$9',
          period: 'month',
          features: ['Feature 1', 'Feature 2'],
          ctaText: 'Get Started',
          highlighted: false,
        },
        {
          name: 'Pro',
          price: '$29',
          period: 'month',
          features: ['All Basic', 'Feature 3', 'Feature 4'],
          ctaText: 'Get Started',
          highlighted: true,
        },
      ],
    },
  },
  {
    id: 'comparison',
    name: 'Comparison Table',
    description: 'Feature comparison grid',
    icon: Table,
    category: 'data',
    defaultContent: {
      heading: 'Compare Plans',
      features: ['Feature 1', 'Feature 2', 'Feature 3'],
      plans: [
        { name: 'Basic', values: [true, false, false] },
        { name: 'Pro', values: [true, true, false] },
        { name: 'Enterprise', values: [true, true, true] },
      ],
    },
  },

  // Social Blocks
  {
    id: 'social-links',
    name: 'Social Links',
    description: 'Social media icon links',
    icon: Share2,
    category: 'social',
    defaultContent: {
      links: [
        { platform: 'twitter', url: '' },
        { platform: 'facebook', url: '' },
        { platform: 'instagram', url: '' },
        { platform: 'linkedin', url: '' },
      ],
      style: 'icons',
      size: 'medium',
    },
  },
  {
    id: 'social-feed',
    name: 'Social Feed',
    description: 'Embedded social media feed',
    icon: Newspaper,
    category: 'social',
    defaultContent: {
      platform: 'instagram',
      username: '',
      count: 6,
    },
  },
  {
    id: 'share-buttons',
    name: 'Share Buttons',
    description: 'Social sharing buttons',
    icon: Share2,
    category: 'social',
    defaultContent: {
      platforms: ['twitter', 'facebook', 'linkedin', 'email'],
      style: 'buttons',
    },
  },
  {
    id: 'reviews',
    name: 'Reviews',
    description: 'Customer reviews with ratings',
    icon: Star,
    category: 'social',
    defaultContent: {
      heading: 'Customer Reviews',
      reviews: [],
      showRating: true,
      allowSubmit: false,
    },
  },

  // Commerce Blocks
  {
    id: 'product-card',
    name: 'Product Card',
    description: 'Single product display',
    icon: Box,
    category: 'commerce',
    defaultContent: {
      productId: '',
      showPrice: true,
      showDescription: true,
      showButton: true,
    },
  },
  {
    id: 'product-grid',
    name: 'Product Grid',
    description: 'Multiple products grid',
    icon: LayoutGrid,
    category: 'commerce',
    defaultContent: {
      products: [],
      columns: 4,
      showFilters: false,
    },
  },
  {
    id: 'featured-product',
    name: 'Featured Product',
    description: 'Highlighted product showcase',
    icon: Award,
    category: 'commerce',
    defaultContent: {
      productId: '',
      variant: 'hero',
      showGallery: true,
    },
  },

  // Form Blocks
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Pre-built contact form',
    icon: Mail,
    category: 'forms',
    defaultContent: {
      heading: 'Get in Touch',
      fields: ['name', 'email', 'message'],
      submitText: 'Send Message',
      successMessage: 'Thank you for your message!',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter Signup',
    description: 'Email subscription form',
    icon: Mail,
    category: 'forms',
    defaultContent: {
      heading: 'Subscribe to Our Newsletter',
      description: 'Get the latest updates delivered to your inbox.',
      buttonText: 'Subscribe',
      placeholder: 'Enter your email',
    },
  },
  {
    id: 'form-builder',
    name: 'Custom Form',
    description: 'Build custom forms',
    icon: FileText,
    category: 'forms',
    defaultContent: {
      fields: [],
      submitText: 'Submit',
      successMessage: 'Form submitted successfully!',
    },
  },
  {
    id: 'search',
    name: 'Search Box',
    description: 'Search input with suggestions',
    icon: Globe,
    category: 'forms',
    defaultContent: {
      placeholder: 'Search...',
      showSuggestions: true,
      searchType: 'site',
    },
  },

  // Special Blocks
  {
    id: 'code',
    name: 'Code Block',
    description: 'Syntax highlighted code',
    icon: Code,
    category: 'content',
    defaultContent: {
      code: '// Your code here',
      language: 'javascript',
      showLineNumbers: true,
      theme: 'dark',
    },
  },
  {
    id: 'embed',
    name: 'Embed',
    description: 'Embed external content',
    icon: Code,
    category: 'media',
    defaultContent: {
      embedCode: '',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'html',
    name: 'Custom HTML',
    description: 'Raw HTML content',
    icon: Code,
    category: 'content',
    defaultContent: {
      html: '',
    },
  },
];

export const getBlocksByCategory = (category: BlockCategory): BlockType[] => {
  return blockTypes.filter((block) => block.category === category);
};

export const getBlockById = (id: string): BlockType | undefined => {
  return blockTypes.find((block) => block.id === id);
};
