/**
 * Living Codex Assessment Engine — Domains 1-4
 * Section 1: Voice & Visibility
 * Section 5: Survival Archetypes
 * Section 2: Relational Patterns
 * Section 3: Wound Imprints
 *
 * All questions written in the Just Empower voice: invitational, resonance-based, never clinical.
 * Scoring reflects the Shadow ↔ Threshold ↔ Gift spectrum across archetype + wound + mirror patterns.
 */

export interface AssessmentQuestion {
  id: string;
  section: number;
  questionNumber: number;
  invitationText: string;
  guidanceNote: string;
  answers: AssessmentAnswer[];
  isGhost: boolean;
}

export interface AssessmentAnswer {
  code: 'A' | 'B' | 'C' | 'D' | 'E';
  text: string;
  spectrumDepth: 'shadow' | 'threshold' | 'gift' | 'ghost';
  primaryArchetype: string | null;
  secondaryArchetype: string | null;
  woundImprint: string | null;
  mirrorPattern: string | null;
  siCode: string | null;
}

// ============================================================================
// DOMAIN 1: PRESENT STATE — Voice & Visibility (Section 1, Questions 1-11)
// ============================================================================
// Surface where she feels most stuck or activated across 5 resonance areas

export const DOMAIN_1_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'S1_Q1',
    section: 1,
    questionNumber: 1,
    invitationText:
      'Before I speak something true — something that actually matters — I notice…',
    guidanceNote:
      '✦ Let yourself arrive at the moment. Not the idea of speaking — the actual second before it.',
    answers: [
      {
        code: 'A',
        text: 'A quiet flinch. Like my body already knows the cost of saying it out loud.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Shame-Defense Reflex',
        mirrorPattern: 'Silence-as-Safety Reflex',
        siCode: null,
      },
      {
        code: 'B',
        text: `An urge to soften it, qualify it — make sure it won't land too hard.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Conditional Worth Coding',
        mirrorPattern: 'Adaptive Camouflage Pattern',
        siCode: null,
      },
      {
        code: 'C',
        text: 'A steadiness. I may not know how it will land, but I know it needs to be said.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Truth Integrity Activation',
        mirrorPattern: 'Truth-Claiming Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: 'A rush of heat — like the words might come out sharper than I mean.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Rejection Imprint',
        mirrorPattern: 'Criticism-Armoring Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Nothing, really. I've learned to say what's expected without feeling much either way.`,
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q2',
    section: 1,
    questionNumber: 2,
    invitationText:
      'When I imagine being truly seen — not judged, just witnessed — the feeling that comes up is…',
    guidanceNote:
      '✦ Not what you think should happen. What actually moves in your nervous system at that image.',
    answers: [
      {
        code: 'A',
        text: `Terror, actually. Like I'd disappear if someone really saw me.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Existence Denial Pattern',
        mirrorPattern: 'Invisibility-as-Protection Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: 'A need to hide the parts that are messy, difficult, or too much.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Conditional Visibility Wounding',
        mirrorPattern: 'Curated Self-Presentation Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'A kind of opening. Like finally, I could breathe.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Authentic Presence Activation',
        mirrorPattern: 'Witnessed-Being Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Skepticism mixed with frustration. People don't see the whole picture anyway.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Misunderstanding Anticipation',
        mirrorPattern: 'Protective Withdrawal Pattern',
        siCode: null,
      },
      {
        code: 'E',
        text: `Flatness. The idea doesn't really move anything in me.`,
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q3',
    section: 1,
    questionNumber: 3,
    invitationText:
      'When I think about my own needs — speaking them, claiming them — my immediate sense is…',
    guidanceNote:
      '✦ This is about the reflex before the thought. The first wave of feeling.',
    answers: [
      {
        code: 'A',
        text: `Guilt. Like wanting something for myself automatically means I'm selfish.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Needs-Equal-Selfishness Equation',
        mirrorPattern: 'Self-Abandonment Pattern',
        siCode: null,
      },
      {
        code: 'B',
        text: `Defiance mixed with fear. If I ask, I'll either be rejected or owe someone.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Conditional Care Imprint',
        mirrorPattern: 'Transactional Relationship Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Clarity. My needs matter, and speaking them is an act of wisdom.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Self-Honoring Integration',
        mirrorPattern: 'Authentic-Need Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Numbness. I've stopped checking in with what I actually need.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Needs-Suppression Pattern',
        mirrorPattern: 'Disconnected-Desire Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Confusion. I'm not sure what my needs are anymore.`,
        spectrumDepth: 'threshold',
        primaryArchetype: 'The Shape-Shifter',
        secondaryArchetype: 'The Lost One',
        woundImprint: 'Self-Disconnect Disorientation',
        mirrorPattern: 'Identity-Fragmentation Pattern',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q4',
    section: 1,
    questionNumber: 4,
    invitationText:
      `In moments when I'm excited or passionate about something, I find myself…`,
    guidanceNote:
      '✦ Not the conversation about it. What happens in your body and energy when the aliveness shows up.',
    answers: [
      {
        code: 'A',
        text: `Quickly dimming it down so I don't overwhelm people with my intensity.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Intensity-as-Burden Coding',
        mirrorPattern: 'Dampening-Own-Aliveness Pattern',
        siCode: null,
      },
      {
        code: 'B',
        text: `Bracing for someone to diminish it or tell me I'm being unrealistic.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Enthusiasm-Crushing Wound',
        mirrorPattern: 'Preemptive-Defense Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Letting it move through me, trusting it to find its own expression.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Aliveness Integration',
        mirrorPattern: 'Authentic-Expression Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: 'Pushing it harder, trying to convince others of its importance.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Validation-Seeking Drive',
        mirrorPattern: 'Proving-Worth Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: 'Disconnected. Passion feels like a distant memory for me.',
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q5',
    section: 1,
    questionNumber: 5,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on resonance patterns from Q1-Q4.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S1_Q6',
    section: 1,
    questionNumber: 6,
    invitationText:
      'When I look at other women who seem confident and rooted, my honest first thought is…',
    guidanceNote:
      '✦ Not the story you tell yourself. The raw, unfiltered first response.',
    answers: [
      {
        code: 'A',
        text: `"I could never be like that. It's not in me."`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Inherent-Inability Belief',
        mirrorPattern: 'Fixed-Limitation Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `"There's probably a cost to that I don't see. Nobody's actually that okay."`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Trust-Dissolution Wound',
        mirrorPattern: 'Hidden-Cost Vigilance Pattern',
        siCode: null,
      },
      {
        code: 'C',
        text: '"I see something I recognize in myself. That could be me too."',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Possibility Recognition Activation',
        mirrorPattern: 'Mirror-Possibility Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `"She's doing it wrong. That kind of confidence usually alienates people."`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Confidence-as-Threat Imprint',
        mirrorPattern: 'Deflection-Criticism Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: 'No clear thought. Just a vague sense of distance from the whole thing.',
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q7',
    section: 1,
    questionNumber: 7,
    invitationText:
      'The feeling I carry most often about how I come across to others is…',
    guidanceNote:
      '✦ Not what you know intellectually. The emotional baseline that sits underneath.',
    answers: [
      {
        code: 'A',
        text: `That I'm too much in some way — too intense, too sensitive, too needy.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Excess-Self Imprint',
        mirrorPattern: 'Burden-Belief Pattern',
        siCode: null,
      },
      {
        code: 'B',
        text: `That I need to stay vigilant or I'll be exposed for something.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Exposure-Anxiety Wound',
        mirrorPattern: 'Vigilant-Defense Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: `That I'm genuinely me, and that's enough. The right people will meet me there.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Self-Acceptance Integration',
        mirrorPattern: 'Authentic-Presence Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: 'That people are judging me or finding me lacking.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Judgment-Anticipation Wound',
        mirrorPattern: 'Inferiority-Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `No real feeling about it. I'm kind of blank on how I'm perceived.`,
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q8',
    section: 1,
    questionNumber: 8,
    invitationText:
      'If I were to claim something I really believe in — out loud, without hedging — I would worry that…',
    guidanceNote:
      `✦ Let the worry surface without judging it. What's the core fear underneath?`,
    answers: [
      {
        code: 'A',
        text: `People would think I'm arrogant or that I'm claiming a certainty I can't prove.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Authority-Illegitimacy Wound',
        mirrorPattern: 'Self-Doubt Suppression Pattern',
        siCode: null,
      },
      {
        code: 'B',
        text: `I'd be proven wrong, and then I'd be vulnerable to attack.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Wrongness-as-Failure Imprint',
        mirrorPattern: 'Preemptive-Armoring Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Nothing, really. My belief is clear, and I can hold it with kindness if others disagree.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Conviction Integration',
        mirrorPattern: 'Rooted-Belief Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `My voice doesn't matter enough for it to even matter what I claim.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Voice-Insignificance Wound',
        mirrorPattern: 'Erasure-Resignation Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `I don't really know what I believe in anymore.`,
        spectrumDepth: 'threshold',
        primaryArchetype: 'The Lost One',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Belief-Dissolution Disorientation',
        mirrorPattern: 'Values-Fragmentation Pattern',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q9',
    section: 1,
    questionNumber: 9,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on resonance patterns from Q6-Q8.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S1_Q10',
    section: 1,
    questionNumber: 10,
    invitationText:
      'The relationship between my inner truth and what I actually express in the world feels like…',
    guidanceNote:
      '✦ Not the gap you judge yourself for. The felt sense of that distance.',
    answers: [
      {
        code: 'A',
        text: `A chasm. What I actually feel is so far from what I say that I'm not even sure who I am anymore.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Self-Fragmentation Wound',
        mirrorPattern: 'Fractured-Identity Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: 'A necessary edit. I carry my truth, but I release it selectively for safety.',
        spectrumDepth: 'threshold',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Contextualized Truth Expression',
        mirrorPattern: 'Wisdom-in-Discernment Pattern',
        siCode: null,
      },
      {
        code: 'C',
        text: `An alignment. I speak what's true, and it lands as my authenticity.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Truth-Expression Integration',
        mirrorPattern: 'Integrated-Authenticity Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Exhausting. I have to be on guard constantly so the wrong truth doesn't slip out.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Expression-Policing Wound',
        mirrorPattern: 'Hypervigilant-Control Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Vague. I can't really tell where the gap is or if it even matters.`,
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S1_Q11',
    section: 1,
    questionNumber: 11,
    invitationText:
      'When I imagine stepping fully into my own authority — speaking, deciding, leading from my own knowing — the first thing I feel is…',
    guidanceNote:
      `✦ Not what's possible or what you "should" feel. What actually arises first?`,
    answers: [
      {
        code: 'A',
        text: `Fear so sharp it almost feels like pain. I don't belong in that space.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Worthiness-Denial Wound',
        mirrorPattern: 'Authority-Erasure Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: 'Guilt. Because that kind of power somehow means someone else loses.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Power-as-Theft Coding',
        mirrorPattern: 'Guilt-Bound Authority Pattern',
        siCode: null,
      },
      {
        code: 'C',
        text: 'An exhale. Like finally, I get to be the one directing my own life.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Authority Integration',
        mirrorPattern: 'Sovereign-Self Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Skepticism. I don't trust my own judgment. I'll probably get it wrong.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Self-Trust Erosion',
        mirrorPattern: 'Judgment-Doubting Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Nothing. The image is too abstract. It doesn't connect to anything real in me.`,
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Lost One',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },
];

// ============================================================================
// DOMAIN 2: NERVOUS SYSTEM BASELINE — Survival Archetypes (Section 5, Q1-11)
// ============================================================================
// Map her default regulation patterns: freeze, fight, collapse, hypervigilance, regulated

export const DOMAIN_2_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'S5_Q1',
    section: 5,
    questionNumber: 1,
    invitationText:
      `When something unexpected or threatening happens, my body's first move is to…`,
    guidanceNote:
      '✦ Watch what happens before your mind has time to respond. The automatic reflex.',
    answers: [
      {
        code: 'A',
        text: 'Go very still. Get quiet. Disappear into observation mode.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Freeze-Response Imprint',
        mirrorPattern: 'Protective Stillness Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'B',
        text: `Heat up. Feel the surge to push back, defend, correct what's wrong.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Fight-Activation Wound',
        mirrorPattern: 'Reactive-Defense Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: `Check in with myself. Notice what's happening and choose my response.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Conscious-Response Integration',
        mirrorPattern: 'Regulated-Choice Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'D',
        text: `Go blank or numb. Like the lights go out and I'm not really here.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Collapse-Dissociation Wound',
        mirrorPattern: 'Shutdown Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: `Scan for danger. My attention goes everywhere looking for what's wrong.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Hypervigilance Imprint',
        mirrorPattern: 'Threat-Detection Loop',
        siCode: 'ns_hypervigilant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q2',
    section: 5,
    questionNumber: 2,
    invitationText:
      'In relationships when someone disagrees with me or pulls away, I typically find myself…',
    guidanceNote:
      '✦ What happens in your nervous system before you even have a thought about it?',
    answers: [
      {
        code: 'A',
        text: 'Shutting down. Pulling inward. Waiting for it to pass.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Withdrawal-Protection Pattern',
        mirrorPattern: 'Isolation-Safety Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'B',
        text: 'Getting activated. Wanting to fix it immediately or prove my point.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Protest-Seeking Drive',
        mirrorPattern: 'Pursuance Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: 'Staying present with both of us. I can hold my perspective and honor theirs.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Relational Integration',
        mirrorPattern: 'Both-And Presence Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'D',
        text: 'Going numb or empty. The disconnection is total, and I stop feeling.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Disconnection Collapse',
        mirrorPattern: 'Abandonment-Numbing Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: 'Analyzing every word, tone, gesture. Looking for the real reason behind it.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Meaning-Seeking Hypervigilance',
        mirrorPattern: 'Decoding Loop',
        siCode: 'ns_hypervigilant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q3',
    section: 5,
    questionNumber: 3,
    invitationText:
      'My baseline state through most of the day is like…',
    guidanceNote:
      '✦ Not what you want it to be. What is the actual felt sense you carry most often?',
    answers: [
      {
        code: 'A',
        text: `Held breath. Waiting. Like I'm perpetually tensing for the next thing to go wrong.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Constant-Vigilance Imprint',
        mirrorPattern: 'Threat-Anticipation Loop',
        siCode: 'ns_hypervigilant',
      },
      {
        code: 'B',
        text: `Low-grade frustration or irritability. Like I'm ready for a fight I haven't had yet.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Stored Reactivity Pattern',
        mirrorPattern: 'Hair-Trigger Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: `Flexible and present. I'm responsive to what's actually happening.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Adaptive Presence Integration',
        mirrorPattern: 'Present-Moment Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'D',
        text: 'Distant. Kind of floating through the day without really feeling connected.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Dissociative Baseline Pattern',
        mirrorPattern: 'Detachment Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: 'Quiet. Withdrawn. Observing everything but not really participating.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Protective Withdrawal Baseline',
        mirrorPattern: 'Spectator Position Loop',
        siCode: 'ns_freeze',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q4',
    section: 5,
    questionNumber: 4,
    invitationText:
      `When I feel someone's anger or disapproval directed at me, what happens in my body is…`,
    guidanceNote:
      '✦ Not what you think about it. The physical, immediate sensation.',
    answers: [
      {
        code: 'A',
        text: 'Contraction. Everything in me wants to hide or make myself smaller.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Rejection-Flinch Imprint',
        mirrorPattern: 'Shrinking Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'B',
        text: 'Surge. My body tenses up, ready to push back or explain.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Counter-Attack Readiness',
        mirrorPattern: 'Defensive Mobilization Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: 'Steadiness. I can feel it land without it destabilizing me.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Emotional Resilience Integration',
        mirrorPattern: 'Stable-Ground Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'D',
        text: `Shutdown. Like an internal switch flips and I'm just… blank.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Protective Numbness Pattern',
        mirrorPattern: 'Emotional Cutoff Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: `Alert. Every sense sharpens. I'm trying to figure out what I did wrong.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Self-Blame Hypervigilance',
        mirrorPattern: 'Fault-Finding Loop',
        siCode: 'ns_hypervigilant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q5',
    section: 5,
    questionNumber: 5,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on nervous system patterns from Q1-Q4.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S5_Q6',
    section: 5,
    questionNumber: 6,
    invitationText:
      'After a conflict or stressful interaction, my nervous system needs…',
    guidanceNote:
      '✦ What actually settles you? Not what you think you "should" do.',
    answers: [
      {
        code: 'A',
        text: 'Complete withdrawal. Time alone, silence, no contact until I can manage my feelings.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Isolation-Based Recovery Pattern',
        mirrorPattern: 'Solo-Healing Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'B',
        text: 'To process it right away — talk it out, fix it, get resolution immediately.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Immediate-Resolution Drive',
        mirrorPattern: 'Urgency-to-Fix Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: 'Self-compassion and perspective. I can sit with it and let it integrate.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Integrated Recovery Capacity',
        mirrorPattern: 'Self-Soothing Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'D',
        text: 'Numbness to wear off. Everything feels too heavy until I can feel nothing again.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Dissociation-Dependent Recovery',
        mirrorPattern: 'Numb-Then-Feel Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: 'To understand what happened. Analysis, understanding what I missed or did wrong.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Intellectual-Processing Dependency',
        mirrorPattern: 'Over-Analysis Loop',
        siCode: 'ns_hypervigilant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q7',
    section: 5,
    questionNumber: 7,
    invitationText:
      `When I'm around people who are very calm and grounded, I tend to…`,
    guidanceNote:
      '✦ What actually happens to your nervous system in those moments?',
    answers: [
      {
        code: 'A',
        text: 'Mirror their calm. Like their regulation gives me permission to settle.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Relational Co-Regulation Capacity',
        mirrorPattern: 'Resonance Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'B',
        text: 'Feel restless or impatient. Their calmness makes me feel like something needs to happen.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Restlessness Activation Pattern',
        mirrorPattern: 'Motion-Seeking Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: `Disconnected. Their peace is so foreign it feels like it's not really available to me.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Peace-Inaccessibility Wound',
        mirrorPattern: 'Outsider-Position Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'D',
        text: `Suspicious. Like they're hiding something or not being fully honest.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Trust-Disruption Imprint',
        mirrorPattern: 'Hidden-Cost Vigilance',
        siCode: 'ns_hypervigilant',
      },
      {
        code: 'E',
        text: `Empty. Their grounding doesn't reach me because I'm already checked out.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Dissociative Barrier Pattern',
        mirrorPattern: 'Unreachable Loop',
        siCode: 'ns_collapse',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q8',
    section: 5,
    questionNumber: 8,
    invitationText:
      'My relationship to control is…',
    guidanceNote:
      `✦ Not morally. Just what's true about how you move in the world.`,
    answers: [
      {
        code: 'A',
        text: `I need to let go. I can't control outcomes, and my body knows it's safer when I'm not trying.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Surrender Integration',
        mirrorPattern: 'Trust-in-Process Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'B',
        text: `I need a lot of it. Without knowing what's coming, my nervous system is in overdrive.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Control-Dependent Safety Coding',
        mirrorPattern: 'Predictability Obsession Loop',
        siCode: 'ns_hypervigilant',
      },
      {
        code: 'C',
        text: 'I oscillate. Sometimes I grip everything, sometimes I give up entirely.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shape-Shifter',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Control-Collapse Oscillation',
        mirrorPattern: 'All-or-Nothing Pattern',
        siCode: 'ns_fight',
      },
      {
        code: 'D',
        text: `I've given up trying. There's no point — things happen to me regardless.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Powerlessness Resignation',
        mirrorPattern: 'Victim-Position Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: `I retreat from situations where I can't control the outcome.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Uncertainty-Avoidance Pattern',
        mirrorPattern: 'Withdrawal-from-Risk Loop',
        siCode: 'ns_freeze',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q9',
    section: 5,
    questionNumber: 9,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on nervous system patterns from Q6-Q8.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S5_Q10',
    section: 5,
    questionNumber: 10,
    invitationText:
      'When things feel uncertain or chaotic around me, my go-to move is to…',
    guidanceNote:
      '✦ What does your body automatically reach for first?',
    answers: [
      {
        code: 'A',
        text: `Step back and breathe. Create space so I can see what's actually happening.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Grounded Response Capacity',
        mirrorPattern: 'Clear-Seeing Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'B',
        text: `Jump in and try to order things, fix what's wrong, restore control.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Chaos-Intolerance Drive',
        mirrorPattern: 'Hyper-Organization Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: 'Get very quiet and still, wait and observe until I understand the pattern.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Protective Observation Pattern',
        mirrorPattern: 'Cautious-Witness Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'D',
        text: 'Scan for threat — what could go wrong? What am I missing?',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Threat-Focused Hypervigilance',
        mirrorPattern: 'Worst-Case-Anticipation Loop',
        siCode: 'ns_hypervigilant',
      },
      {
        code: 'E',
        text: 'Withdraw completely. The chaos is too much, so I just check out.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Overwhelm-Based Dissociation',
        mirrorPattern: 'Complete-Shutdown Loop',
        siCode: 'ns_collapse',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S5_Q11',
    section: 5,
    questionNumber: 11,
    invitationText:
      'The most natural pace for my nervous system feels like…',
    guidanceNote:
      `✦ Not what you're forced to do. What feels homeostatic — like you can stay there.`,
    answers: [
      {
        code: 'A',
        text: 'Slow. Quiet. Solitary. I need space between interactions to recharge.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Withdrawal-as-Baseline Pattern',
        mirrorPattern: 'Isolation-Preference Loop',
        siCode: 'ns_freeze',
      },
      {
        code: 'B',
        text: 'Fast and moving. Stimulation, activity, momentum. Stillness feels dangerous.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Motion-Dependent Safety',
        mirrorPattern: 'Avoidance-Through-Action Loop',
        siCode: 'ns_fight',
      },
      {
        code: 'C',
        text: `Responsive. I can shift pace based on what's needed, but I have a calm center.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Adaptive Regulation Integration',
        mirrorPattern: 'Flexible-Responsiveness Field',
        siCode: 'ns_regulated',
      },
      {
        code: 'D',
        text: `Checked out. Like I'm running at a distance from everything happening.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Dissociative Baseline Pattern',
        mirrorPattern: 'Autopilot Loop',
        siCode: 'ns_collapse',
      },
      {
        code: 'E',
        text: 'Uncertain. I go back and forth between needing calm and needing stimulation.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shape-Shifter',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Dysregulation Oscillation',
        mirrorPattern: 'Unstable-Baseline Loop',
        siCode: 'ns_hypervigilant',
      },
    ],
    isGhost: false,
  },
];

// ============================================================================
// DOMAIN 3: ATTACHMENT + RELATIONAL THEMES (Section 2, Questions 1-11)
// ============================================================================
// Surface relational wound patterns: anxious, avoidant, secure, porous boundaries, self-abandonment

export const DOMAIN_3_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'S2_Q1',
    section: 2,
    questionNumber: 1,
    invitationText:
      'In close relationships, my fear is most often that…',
    guidanceNote:
      '✦ Not the fear you think is "rational." The one that wakes you up at night.',
    answers: [
      {
        code: 'A',
        text: `They'll leave me. That I'm not enough to keep them close.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Abandonment Anxiety',
        mirrorPattern: 'Seeking-Reassurance Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: `They'll consume me or I'll lose myself trying to meet their needs.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Engulfment Fear',
        mirrorPattern: 'Self-Protection Distance Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'Nothing, really. I trust we can work through conflict together.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Secure Relational Base',
        mirrorPattern: 'Trust-and-Repair Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: `That I'm manipulating them somehow without knowing it.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Hidden-Harm Vigilance',
        mirrorPattern: 'Self-Blame-in-Relationships Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'E',
        text: `I don't really form close connections. Relationships feel distant or obligatory.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Relational Numbness',
        mirrorPattern: 'Disconnection-as-Safety Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q2',
    section: 2,
    questionNumber: 2,
    invitationText:
      'When someone I care about is upset, my immediate impulse is to…',
    guidanceNote:
      '✦ Not what you think you should do. What pulls at you first?',
    answers: [
      {
        code: 'A',
        text: `Fix it, soothe it, make sure they're okay. Their upset destabilizes me until they're better.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Caretaker Encoding',
        mirrorPattern: 'Other-Focused Regulation Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: 'Pull back. Their emotions feel like too much, and I need distance.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Emotional Overwhelm Response',
        mirrorPattern: 'Protective-Withdrawal Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'Hold space for them while staying grounded in myself.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Compassionate Presence Integration',
        mirrorPattern: 'Witnessing-with-Boundaries Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: 'Assume I caused it somehow. That I should have done more to prevent it.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Responsibility Overextension',
        mirrorPattern: 'Self-Blame-as-Connection Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'E',
        text: 'Feel nothing much. Their upset is their problem to manage.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Emotional Detachment Pattern',
        mirrorPattern: 'Indifference-Armor Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q3',
    section: 2,
    questionNumber: 3,
    invitationText:
      'My boundaries in relationships tend to look like…',
    guidanceNote:
      `✦ Not what you want them to be. What's actually true in how you operate.`,
    answers: [
      {
        code: 'A',
        text: `Soft. I say yes when I mean no. I give more than I'm asked.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Boundary Permeability',
        mirrorPattern: 'Self-Abandoning Loop',
        siCode: 'boundary_porous',
      },
      {
        code: 'B',
        text: 'High walls. I keep people at a distance and rarely let them in.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Protective Boundary Rigidity',
        mirrorPattern: 'Isolation-Through-Boundaries Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'Clear and responsive. I know what I can offer and I honor that.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Boundary Integration',
        mirrorPattern: 'Clear-Saying Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: `Confused. I don't really know where I end and others begin.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Self-Boundary Dissolution',
        mirrorPattern: 'Identity-Merging Loop',
        siCode: 'boundary_porous',
      },
      {
        code: 'E',
        text: 'Rigid. I keep myself inaccessible because anything less feels unsafe.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Hypervigilant Boundary Defense',
        mirrorPattern: 'Impenetrable-Wall Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q4',
    section: 2,
    questionNumber: 4,
    invitationText:
      `When someone doesn't text me back quickly or seems distant, I…`,
    guidanceNote:
      '✦ Let yourself notice the actual sensation before the story kicks in.',
    answers: [
      {
        code: 'A',
        text: 'Spiral. Did I say something wrong? Are they losing interest? I replay everything.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Rejection Sensitivity Wound',
        mirrorPattern: 'Seeking-Safety-in-Reassurance Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: `Don't really notice or care. I'm used to people not being consistently available.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Detached-Expectation Pattern',
        mirrorPattern: 'Preemptive-Withdrawal Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: `Check in with myself first. Maybe they're busy. I can handle the uncertainty.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Secure Response Integration',
        mirrorPattern: 'Trust-Tolerance Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: 'Blame myself. I probably asked too much or put them out somehow.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Self-Blame-in-Relational Gaps',
        mirrorPattern: 'Responsibility-Acceptance Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'E',
        text: `Feel nothing. Absence is just absence. It doesn't mean anything.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Relational Numbness',
        mirrorPattern: 'Meaning-Denial Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q5',
    section: 2,
    questionNumber: 5,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on attachment patterns from Q1-Q4.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S2_Q6',
    section: 2,
    questionNumber: 6,
    invitationText:
      `When I'm with someone who has a different need or boundary than me, I find myself…`,
    guidanceNote:
      '✦ Not the ideal response. What actually happens in you?',
    answers: [
      {
        code: 'A',
        text: 'Shifting my needs to match theirs. Their comfort becomes more important than mine.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Other-Prioritization Coding',
        mirrorPattern: 'Self-Erasure Loop',
        siCode: 'self_abandonment',
      },
      {
        code: 'B',
        text: `Withdrawing or finding reasons to leave. I can't adapt to anyone else's needs.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Inflexible Autonomy Pattern',
        mirrorPattern: 'Distance-When-Incongruent Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'Curious. I can hold both our needs and find what works for us both.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Collaborative Integration',
        mirrorPattern: 'Both-And Negotiation Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: `Confused. I don't know whose needs should come first.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Hierarchical-Need Confusion',
        mirrorPattern: 'Paralyzed-Choice Loop',
        siCode: 'self_abandonment',
      },
      {
        code: 'E',
        text: `Believing mine are always wrong. If there's a difference, I'm probably the problem.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Need-as-Wrongness Belief',
        mirrorPattern: 'Default-Blame Loop',
        siCode: 'self_abandonment',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q7',
    section: 2,
    questionNumber: 7,
    invitationText:
      'In conversation, if someone disagrees with me, I typically…',
    guidanceNote:
      '✦ What happens before you even think about what to do?',
    answers: [
      {
        code: 'A',
        text: `Scramble to explain myself or convince them they're wrong. I need them to understand.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Validation-Seeking Drive',
        mirrorPattern: 'Consensus-Dependence Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: 'Shut down or get defensive. Like I need to protect my position.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Threat-Response Coding',
        mirrorPattern: 'Protective-Argumentation Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: `Stay curious. Their view adds information. We don't have to agree.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Difference-Tolerance Integration',
        mirrorPattern: 'Secure-Disagreement Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: `Assume they're right and I'm wrong. Give up my position to keep peace.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Conflict-Avoidance-via-Surrender',
        mirrorPattern: 'Consistency-Abandonment Loop',
        siCode: 'self_abandonment',
      },
      {
        code: 'E',
        text: `Feel nothing. Disagreement doesn't reach me because I'm already disconnected.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Engagement Numbness',
        mirrorPattern: 'Presence-Absence Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q8',
    section: 2,
    questionNumber: 8,
    invitationText:
      'I notice I struggle most with relationships where the other person…',
    guidanceNote:
      '✦ Not morally. Just what pattern trips you up again and again.',
    answers: [
      {
        code: 'A',
        text: 'Has unpredictable availability or seems unreliable. It destabilizes me.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Inconsistency-Intolerance Wound',
        mirrorPattern: 'Seeking-Stable-Reassurance Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: 'Wants closeness or emotional depth. I feel pressured and need to escape.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Intimacy-Threat Imprint',
        mirrorPattern: 'Intimacy-Avoidance Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'I can show up genuinely. Most of my struggles are external, not relational.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Relational Resilience',
        mirrorPattern: 'Authentic-Connection Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: 'Is honest about their own struggles. I feel responsible for fixing it.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Caretaker Responsibility Imprint',
        mirrorPattern: 'Obligation-Based-Relating Loop',
        siCode: 'self_abandonment',
      },
      {
        code: 'E',
        text: `I don't really struggle because I don't let relationships get deep enough.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Relational Shallow-Rooting',
        mirrorPattern: 'Surface-Connection-Only Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q9',
    section: 2,
    questionNumber: 9,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on attachment patterns from Q6-Q8.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S2_Q10',
    section: 2,
    questionNumber: 10,
    invitationText:
      'When I think about being fully myself — unfiltered, unedited — in a relationship, I feel…',
    guidanceNote:
      '✦ Not what you think you should feel. The actual texture of that possibility.',
    answers: [
      {
        code: 'A',
        text: `Terrified. They'll see the parts I hide and leave.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Full-Self-Rejection Fear',
        mirrorPattern: 'Conditional-Acceptance Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: `Impossible. I can't be fully myself with anyone. That would be too risky.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Total-Vulnerability Threat',
        mirrorPattern: 'Perpetual-Guard Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'Safe. I can gradually reveal myself and trust them to meet me there.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Authentic Self-Trust',
        mirrorPattern: 'Progressive-Intimacy Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: `Like I'd disappear. I don't really know who I am anymore to show up as.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Self-Dissolution Anxiety',
        mirrorPattern: 'Identity-Loss Loop',
        siCode: 'self_abandonment',
      },
      {
        code: 'E',
        text: `Like I should. But I'm not going to risk it. I've learned my lesson.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Resigned-to-Armor Pattern',
        mirrorPattern: 'Protective-Cynicism Loop',
        siCode: 'attachment_avoidant',
      },
    ],
    isGhost: false,
  },

  {
    id: 'S2_Q11',
    section: 2,
    questionNumber: 11,
    invitationText:
      `The person I'm most afraid of disappointing is…`,
    guidanceNote:
      '✦ Not who you know logically. Who lives in your body as the threat.',
    answers: [
      {
        code: 'A',
        text: `The person I'm trying to get close to. If I disappoint them, they might leave.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Relational Rejection Imprint',
        mirrorPattern: 'Performance-for-Love Loop',
        siCode: 'attachment_anxious',
      },
      {
        code: 'B',
        text: 'Anyone really. So I keep my distance to prevent it.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Universal-Failure Expectation',
        mirrorPattern: 'Preemptive-Withdrawal Loop',
        siCode: 'attachment_avoidant',
      },
      {
        code: 'C',
        text: 'Myself. And I trust that missteps are part of the process.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Self-Compassion Integration',
        mirrorPattern: 'Self-Honoring Field',
        siCode: 'attachment_secure',
      },
      {
        code: 'D',
        text: 'Everyone. And I feel the weight of that constantly.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Omnipresent Responsibility',
        mirrorPattern: 'Burden-Carrying Loop',
        siCode: 'self_abandonment',
      },
      {
        code: 'E',
        text: `I'm not sure. Disappointment feels too abstract for me to connect with.`,
        spectrumDepth: 'ghost',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: false,
  },
];

// ============================================================================
// DOMAIN 4: WOUND IMPRINT SCREENING (Section 3, Questions 1-11)
// ============================================================================
// Identify primary wound imprint categories from the 12-category taxonomy

export const DOMAIN_4_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'S3_Q1',
    section: 3,
    questionNumber: 1,
    invitationText:
      'When I notice a mistake or imperfection in myself, my first feeling is usually…',
    guidanceNote:
      '✦ The raw sensation before any narrative. Just the pure feeling.',
    answers: [
      {
        code: 'A',
        text: `Shame. Like there's something fundamentally wrong with me.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Shame-Core Wound',
        mirrorPattern: 'Fundamental-Deficiency Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `Self-attack. I'm stupid, weak, or careless. I deserve the criticism.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Self-Blame Wound',
        mirrorPattern: 'Internal-Critic Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Curiosity mixed with compassion. What can I learn from this?',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Growth-Oriented Integration',
        mirrorPattern: 'Mistake-as-Information Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: 'Panic. Like I need to fix it immediately so no one finds out.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Exposure-Anxiety Wound',
        mirrorPattern: 'Concealment-Driven Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Nothing much. I don't really register mistakes in myself.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Self-Disconnection Pattern',
        mirrorPattern: 'Avoidance-Through-Numbness Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q2',
    section: 3,
    questionNumber: 2,
    invitationText:
      'When I think about my own power or capability, I feel most…',
    guidanceNote:
      '✦ Not relative to others. Just in yourself alone.',
    answers: [
      {
        code: 'A',
        text: `Doubtful. Like I can't be trusted with power or I'll misuse it.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Self-Trust Erosion Wound',
        mirrorPattern: 'Power-Distrust Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `Insufficient. Like I'm never enough, no matter how hard I try.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Inadequacy-Core Wound',
        mirrorPattern: 'Never-Enough Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Grounded. I know my capacity and can grow within it.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Self-Trust Integration',
        mirrorPattern: 'Capability-Grounding Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Afraid that if I showed my power, I'd be rejected or attacked.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Power-as-Threat Imprint',
        mirrorPattern: 'Strength-Hiding Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Absent. I'm not sure I have any real power.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Lost One',
        woundImprint: 'Powerlessness-Core Wound',
        mirrorPattern: 'Agency-Erasure Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q3',
    section: 3,
    questionNumber: 3,
    invitationText:
      'When I consider being vulnerable with someone, I fear that…',
    guidanceNote:
      '✦ Not judgment. Just the underlying fear in your nervous system.',
    answers: [
      {
        code: 'A',
        text: `I'll be used or hurt. My vulnerability would be weaponized.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Trust-Betrayal Wound',
        mirrorPattern: 'Vulnerability-as-Danger Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `I'll disappear or lose myself. My needs would consume the relationship.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Engulfment-Fear Wound',
        mirrorPattern: 'Disappearance-in-Connection Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Nothing really. Vulnerability is how real connection happens.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Vulnerability-as-Strength Integration',
        mirrorPattern: 'Authentic-Exposure Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `They'll think less of me or see I'm too much to handle.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Conditional-Acceptance Wound',
        mirrorPattern: 'Too-Much Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `I don't really feel vulnerable. It's hard to access that in me.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Emotional-Accessibility Wound',
        mirrorPattern: 'Disconnection-from-Feeling Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q4',
    section: 3,
    questionNumber: 4,
    invitationText:
      'When I receive praise or recognition, I find myself…',
    guidanceNote:
      `✦ What's the automatic impulse before your mind intercepts it?`,
    answers: [
      {
        code: 'A',
        text: `Uncomfortable. Like they're wrong or I don't deserve it.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Silent Flame',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Worthiness-Denial Wound',
        mirrorPattern: 'Praise-Deflection Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `Anxious. Like I need to prove it again or they'll see through me.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Imposter-Syndrome Wound',
        mirrorPattern: 'Constant-Proof-Seeking Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Grateful and grounded. I can receive it without it destabilizing me.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Self-Worth Integration',
        mirrorPattern: 'Recognition-Reception Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Skeptical. People don't really see me, they see a performance.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Authenticity-Doubt Wound',
        mirrorPattern: 'Facade-Recognition Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `Blank. It doesn't really land in me as meaningful.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Numb One',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Meaning-Reception Blockage',
        mirrorPattern: 'Emotional-Flatness Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q5',
    section: 3,
    questionNumber: 5,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on wound patterns from Q1-Q4.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S3_Q6',
    section: 3,
    questionNumber: 6,
    invitationText:
      'When I think about my body or physical being, the primary feeling is…',
    guidanceNote:
      '✦ Not the politics of it. Just the felt sense you carry in your own flesh.',
    answers: [
      {
        code: 'A',
        text: `Disconnected or foreign. Like I'm living in it but not really in it.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Embodiment-Wound',
        mirrorPattern: 'Body-Dissociation Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `Ashamed or judged. Like it's not right or acceptable as it is.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Body-Shame Wound',
        mirrorPattern: 'Body-as-Problem Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Grounded and wise. My body is a source of knowing.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Embodied Wisdom Integration',
        mirrorPattern: 'Body-as-Teacher Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: 'Unsafe or violated. Like something happened that left a mark.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Violation-or-Trauma Wound',
        mirrorPattern: 'Body-as-Threat Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `I don't really register my body. It's background noise.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Lost One',
        woundImprint: 'Somatic-Numbness Wound',
        mirrorPattern: 'Body-Irrelevance Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q7',
    section: 3,
    questionNumber: 7,
    invitationText:
      'The way I relate to success or achievement is…',
    guidanceNote:
      '✦ Not the ideal. The truth of how you actually move toward your own goals.',
    answers: [
      {
        code: 'A',
        text: `I sabotage myself. Like I don't believe I deserve it.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Fault-Bearer',
        woundImprint: 'Self-Sabotage Wound',
        mirrorPattern: 'Success-Fear Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: 'I chase it compulsively. Like my worth depends on achieving.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Achievement-Dependence Wound',
        mirrorPattern: 'Striving-for-Worth Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: `I move toward it steadily, but I'm not defined by it.`,
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Purpose-Aligned Integration',
        mirrorPattern: 'Values-Based Action Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `I give up before I start. Like I can't win anyway.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Learned-Helplessness Wound',
        mirrorPattern: 'Preemptive-Failure Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: 'I avoid it. Success feels too risky or like it requires sacrifice.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Success-Threat Imprint',
        mirrorPattern: 'Achievement-Avoidance Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q8',
    section: 3,
    questionNumber: 8,
    invitationText:
      'When I encounter someone who seems to be thriving, I feel…',
    guidanceNote:
      `✦ Not what's nice. What's actually true in your body.`,
    answers: [
      {
        code: 'A',
        text: 'Envy or resentment. Like they got what should have been mine.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Deprivation-Resentment Wound',
        mirrorPattern: 'Comparison-Devastation Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `Threatened. Like their success diminishes mine or proves I'm failing.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Zero-Sum Belief Wound',
        mirrorPattern: 'Competitive-Threat Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Inspired. I see possibility and it makes my own path clearer.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Inspiration-From-Others Integration',
        mirrorPattern: 'Mirror-Possibility Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Suspicious. They're probably hiding something or got lucky.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Ghost',
        woundImprint: 'Success-Doubt Wound',
        mirrorPattern: 'Legitimacy-Questioning Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: 'Nothing much. Their life and mine feel disconnected.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Numb One',
        woundImprint: 'Relational Numbness',
        mirrorPattern: 'Emotional-Distance Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q9',
    section: 3,
    questionNumber: 9,
    invitationText: '[GHOST QUESTION — Placeholder for integration layer]',
    guidanceNote:
      '✦ This question will be populated by the integration layer based on wound patterns from Q6-Q8.',
    answers: [
      {
        code: 'A',
        text: '[Ghost answer A]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'B',
        text: '[Ghost answer B]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'C',
        text: '[Ghost answer C]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'D',
        text: '[Ghost answer D]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
      {
        code: 'E',
        text: '[Ghost answer E]',
        spectrumDepth: 'ghost',
        primaryArchetype: null,
        secondaryArchetype: null,
        woundImprint: null,
        mirrorPattern: null,
        siCode: null,
      },
    ],
    isGhost: true,
  },

  {
    id: 'S3_Q10',
    section: 3,
    questionNumber: 10,
    invitationText:
      'When I think about my own needs and desires, the feeling is…',
    guidanceNote:
      `✦ Before you edit or judge them. What's the original texture of wanting?`,
    answers: [
      {
        code: 'A',
        text: `Illegitimate. Like my desires are wrong or shouldn't matter.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Desire-Illegitimacy Wound',
        mirrorPattern: 'Want-Suppression Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: 'Dangerous. Like if I want something, it will be taken from me.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Cynic',
        secondaryArchetype: 'The Shielded One',
        woundImprint: 'Deprivation-as-Punishment Wound',
        mirrorPattern: 'Desire-as-Risk Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'Valid and worthy of honoring. I can want something and act on it.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Rooted Flame',
        woundImprint: 'Authentic Desire Integration',
        mirrorPattern: 'Sacred-Wanting Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Absent. I don't really know what I want anymore.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Desire-Disconnection Wound',
        mirrorPattern: 'Want-Void Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: 'Selfish. Like wanting something automatically takes from others.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Pleaser Flame',
        woundImprint: 'Desire-as-Greed Equation',
        mirrorPattern: 'Zero-Sum-Wanting Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },

  {
    id: 'S3_Q11',
    section: 3,
    questionNumber: 11,
    invitationText:
      'The conversation I most avoid having with myself is about…',
    guidanceNote:
      '✦ Not the one you think you should address. The one you keep dodging.',
    answers: [
      {
        code: 'A',
        text: 'What I really want or who I really am. The gap feels too big.',
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Ghost',
        secondaryArchetype: 'The Shape-Shifter',
        woundImprint: 'Self-Truth Avoidance Wound',
        mirrorPattern: 'Identity-Gap Loop',
        siCode: null,
      },
      {
        code: 'B',
        text: `How I've been harmed or where I gave myself away.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Pleaser Flame',
        secondaryArchetype: 'The Burdened Flame',
        woundImprint: 'Self-Betrayal Wound',
        mirrorPattern: 'Harm-Recognition Avoidance Loop',
        siCode: null,
      },
      {
        code: 'C',
        text: 'I can be honest with myself. These conversations inform my path.',
        spectrumDepth: 'gift',
        primaryArchetype: 'The Sovereign',
        secondaryArchetype: 'The Truth-Keeper',
        woundImprint: 'Self-Honesty Integration',
        mirrorPattern: 'Truth-Facing Field',
        siCode: 'SI',
      },
      {
        code: 'D',
        text: `Whether I'm actually failing or if I just believe I am.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Fault-Bearer',
        secondaryArchetype: 'The Cynic',
        woundImprint: 'Self-Assessment Distortion',
        mirrorPattern: 'Failure-Obsession Loop',
        siCode: null,
      },
      {
        code: 'E',
        text: `I don't really have those conversations. Introspection feels risky.`,
        spectrumDepth: 'shadow',
        primaryArchetype: 'The Shielded One',
        secondaryArchetype: 'The Silent Flame',
        woundImprint: 'Self-Knowledge Avoidance',
        mirrorPattern: 'Protective-Numbness Loop',
        siCode: null,
      },
    ],
    isGhost: false,
  },
];
